import { Activity, Guest, Organizer, Sponsor, TimetableEvent } from './types';

export const ACTIVITIES: Activity[] = [
  {
    id: 'act-night-ride',
    title: 'Night Ride',
    category: 'Prime Event',
    description: 'The definitive MTL ROLL experience. A massive, synchronized assault on the city streets under the cover of darkness. High speeds, neon trails, and pure kinetic energy.',
    longDescription: 'The headline event of MTL ROLL 2026. Join over a thousand skaters as we take over Montreal’s high-velocity boulevards. Fully escorted by safety marshals, this synchronized ride spans across major downtown vectors with neon light installations and synchronized mobile sound systems.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    iconName: 'directions_bike', // Will map to Lucide icon Bike or Zap
    difficulty: 'All Levels',
    date: 'Friday & Saturday, Sept 11 & 12',
    time: '20:00 - 23:00',
    location: 'Starts at Verdun Grid Hub',
  },
  {
    id: 'act-mural-ride',
    title: 'Mural Ride',
    category: 'Rides',
    description: "A curated tour through Montreal's most iconic and hidden street art installations. Pace is moderate, visuals are maximum.",
    longDescription: "Explore the legendary street murals of Montreal. This slow-to-moderate paced ride takes you through Saint-Laurent and Mile End back alleys, detailing the history of the city’s underground art scene and culminating in an outdoor gallery social.",
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBo4OsmywxyzTBGMpyJ2bONw_D0vlGKtLZIUtQ4wCtoFmboYAd8JRtC56FQUMeY8x9V8dzM_NfKPZx3nWcaZ-Sl4MOCRIbSLJQWf2iyqQohqSR3A_ehGXIy2s8JKHmB3JdIyFoQFP6DRGkHWg8OZCF8NMnXp-wK4XDzjSuww4NIBVKO79hSU39GeE8hzJPDSmXzxEfLubeML19YdskJ-qsNR1-1XIFxYW_ZjYVFVuti1sqlSA6uLIU0',
    iconName: 'brush', // Lucide Brush / Palette
    difficulty: 'All Levels',
    date: 'Saturday, Sept 12',
    time: '14:00 - 17:00',
    location: 'Starts at Saint-Laurent Metro',
  },
  {
    id: 'act-long-distance',
    title: 'Long Distance',
    category: 'Rides',
    description: 'Test your endurance on a relentless 50km circuit. Strategic pacing and drafting are essential to survive the loop.',
    longDescription: 'A brutal test of mental and physical fortitude. This 50km circuit pushes you across Montreal’s scenic outer canal vectors and port areas. Perfect for marathon speed-skaters and long-frame inline enthusiasts who thrive on drafting and pace control.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBtwBSh3I9965A5VA97GMNT6WPcpuu5lY8I0IjGiK64Fk0WHYIT5lLoUPqdrAuZgT135nCSSYXNEfdmjHaaTmCSimZFNPGifGOgEHqV9Ce7EiT2ka47xYp-GUeXAz7mZOk50o73irbImltxqiiVP2kW6I3JS43Y4XX4P68mZoG07MBWF4_BVlxnFnuICCFniVFHWu74Nsja97XezTH6yQTaucqy6wP_2Gzi8Ppx8r-LeFXGjoDfCTB8',
    iconName: 'route', // Lucide Route / Milestone
    difficulty: 'Tech',
    date: 'Sunday, Sept 13',
    time: '09:00 - 12:00',
    location: 'Starts at Lachine Canal Grid',
  },
  {
    id: 'act-slalom',
    title: 'Slalom',
    category: 'Tech',
    description: 'Precision carving through tightly spaced cones. Requires maximum agility, technical edge control, and intense focus.',
    longDescription: 'For the precision masters. We construct a technical cone grid where competitors showcase speed-slalom, classic freestyle, and battle slalom. Master-class coaching sessions are also held prior to the tournament.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD-_Ict4THRYVHUB8CLRsQjgip0_D30ZyoyF3yuGBHdka_2AoHhMmS9U6mAhb27nWMMs3BBRNqfKVwy6kfq8sz8PmtLkrxyWtaPp4TSQBSk7UMiNpERlxI8-680gry-LjbhUsgZUsqRaHxzTfrRQ6-yh7DOA76n1FMmzJeTY_J-CRZF08Ei8v6bewiMx3ZrF2rSd7FLtZ9MoNHkbLYjc_bqWQis-tSHZlQWJyvXG7ejVkQfcMDwSu2J',
    iconName: 'timeline', // Lucide Sliders / Shuffle
    difficulty: 'Tech',
    date: 'Saturday, Sept 12',
    time: '11:00 - 13:00',
    location: 'Verdun Arena Court',
  },
  {
    id: 'act-jump',
    title: 'Jump',
    category: 'High Risk',
    description: 'Ramp launches and gap clears. Push your aerial limits in a controlled environment with expert spotters.',
    longDescription: 'High-flying gravity-defying action. Using bespoke wooden launch ramps and adjustable high bars, competitors battle for maximum height (Free Jump) and best style trick (High Jump) over simulated urban obstacles.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAcz5koXIDour-9seud2hMpfMyL-_igvkj8j03j20Zl82np7JbR2LTnhd6xlbVKwvbU9LsACykPpKen2VtNbc5FFrl72JyV5zULmrPzmprHSN6Xz5ZsIqK2Ru3HsHTdGaxGLUb8tsP56qQHAuvq9_jEyWiVxo4BIY6rwuwUL2WbKOn3x-9b94cTQj63E3Al0yVXhOMHS3d0ujSQfuGQf_FhLbd1NYV5vjJMu7TSfeZwWXMuIYwWhj8T',
    iconName: 'flight_takeoff', // Lucide TrendingUp / Rocket
    difficulty: 'High Risk',
    date: 'Sunday, Sept 13',
    time: '15:00 - 18:00',
    location: 'Verdun Outdoor Pump Circuit',
  },
  {
    id: 'act-wizard',
    title: 'Wizard',
    category: 'Style',
    description: 'Flow state skating. Link complex transitions, spins, and footwork on flat ground with long-frame setups.',
    longDescription: 'Explore flatland artistry. Led by style pioneers, this session teaches wizard-style movements, swivels, gazelles, lions, and artistic carve combinations. Perfect for those with multi-rockered long frames looking to unlock flow state.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGtm6jK2gS9pavNm6jz5SH78XNkpBRlByAo36kawzTStCMCJWYmZDHSmFxJA65lvTw8t7zt04GLIQyw1RzK2wuO05f9ZUaAlWtvbO0aBn3eJYWya9H6nsp3DxS7hNByQEjXU3KTQwIMIXkc0poEBPheC_ZLEE9T_YNzd8qje1-WGGFqKJmuIpyaCUb_hfOnjQh6gB6tvT__tk1NoJ2zBkZsKku1Z9MZ1hdAsg0SCfd8F8nraYwsNCR',
    iconName: 'auto_awesome', // Lucide Sparkles
    difficulty: 'Style',
    date: 'Saturday, Sept 12',
    time: '16:30 - 18:00',
    location: 'Verdun Waterfront Plaza',
  }
];

export const GUESTS: Guest[] = [
  {
    id: 'guest-dave',
    name: 'Dave',
    tags: ['PUMPTRACK'],
    image: '/guests/dave.jpg',
    instagramUrl: 'https://www.instagram.com/85pereira/',
  },
  {
    id: 'guest-melina',
    name: 'Melina',
    tags: ['PUMPTRACK'],
    image: '/guests/melina.jpg',
    instagramUrl: 'https://www.instagram.com/_melina_rc/',
  },
  {
    id: 'guest-seb',
    name: 'Seb',
    tags: ['JUMP', 'WIZARD', 'SPEAKER'],
    image: '/guests/seb.jpg',
    instagramUrl: 'https://www.instagram.com/sebl988/',
  },
  {
    id: 'guest-karen',
    name: 'Karen',
    tags: ['SLALOM'],
    image: '/guests/karen.jpg',
    instagramUrl: 'https://www.instagram.com/karenest9/',
  },
  {
    id: 'guest-kaia',
    name: 'Kaia',
    tags: ['SLALOM'],
    image: '/guests/kaia.png',
    instagramUrl: 'https://www.instagram.com/kaia_baird_/',
  },
  {
    id: 'guest-saul',
    name: 'Saul',
    tags: ['SLIDE'],
    image: '/guests/saul.jpg',
    instagramUrl: 'https://www.instagram.com/saul_gomez_lopez/',
  },
  {
    id: 'guest-xav',
    name: 'Xavier',
    tags: ['SKATEPARK'],
    image: '/guests/xavier.jpg',
    instagramUrl: 'https://www.instagram.com/crazyxav.art/',
  },
  {
    id: 'guest-emile',
    name: 'Émile',
    tags: ['FREESTYLE'],
    image: '/guests/emile.jpg',
    instagramUrl: 'https://www.instagram.com/emile_besh/',
  },
  {
    id: 'guest-marly',
    name: 'Marly',
    tags: ['ROLLER_DANCE'],
    image: '/guests/marly.jpg',
    instagramUrl: 'https://www.instagram.com/skatewithmarly/',
  },
  {
    id: 'guest-skatespace',
    name: 'SKATESPACE',
    tags: ['INTRO_TO_SKATING', 'ROLLER_DANCE', 'SLALOM', 'GAMES'],
    image: '/guests/skatespace.jpg',
    instagramUrl: 'https://www.instagram.com/skatespace.ca/',
  },
  {
    id: 'guest-vrl',
    name: 'VRL',
    tags: ['SPEED_SKATING'],
    image: '/guests/vrl.png',
    instagramUrl: 'https://www.instagram.com/vrlroller/',
  },
];

export const ORGANIZERS: Organizer[] = [
  {
    id: 'org-rolling-tribes',
    name: 'Rolling Tribes',
    roleDescription: {
      EN: 'The architectural minds behind the night. Rolling Tribes is a collective of velocity addicts and urban navigators dedicated to reclaiming the concrete sprawl. They engineer the routes, establish the protocols, and ensure the grid remains electrified for every rider entering the zone.',
      FR: "Les architectes au cœur de l'événement. Rolling Tribes est un collectif de passionnés de vitesse et de navigateurs urbains dévoués à s'approprier les espaces urbains. Ils conçoivent les parcours, établissent les protocoles de sécurité et veillent à dynamiser chaque kilomètre pour tous les patineurs.",
      ES: 'Las mentes maestras detrás del evento. Rolling Tribes es un colectivo de apasionados por la velocidad y exploradores urbanos dedicados a conquistar el asfalto. Diseñan las rutas, establecen los protocolos de seguridad y aseguran que la energía se mantenga al máximo para cada participante.',
    },
    entityId: 'RLL_TRB_01',
    image: '/organizers/rolling_tribes_logo.jpg',
    tags: ['ROUTING', 'LOGISTICS', 'OVERSEER'],
    website: 'https://rollingtribes.com',
    instagramUrl: 'https://www.instagram.com/rollingtribes/',
  },
  {
    id: 'org-city-verdun',
    name: 'Arrondissement de Verdun',
    roleDescription: {
      EN: 'Official municipal host and territorial partner for MONTRÉAL ROLL 2026. Arrondissement de Verdun powers the grid by opening prime waterfront plazas, pump track hubs, and protected urban corridors, championing active mobility and community skate culture.',
      FR: "Arrondissement hôte officiel et partenaire territorial de MONTRÉAL ROLL 2026. L'arrondissement de Verdun soutient le festival en ouvrant ses magnifiques berges, ses installations de pumptrack et ses corridors urbains protégés, valorisant la mobilité active et la culture du patinage.",
      ES: 'Anfitrión municipal oficial y aliado territorial de MONTRÉAL ROLL 2026. La alcaldía de Verdun impulsa el evento abriendo sus plazas costeras, circuitos de pumptrack y corredores urbanos protegidos, promoviendo la movilidad activa y la cultura del patinaje.',
    },
    entityId: 'ARR_VRDN_02',
    image: '/organizers/verdun_logo.svg',
    tags: ['HOST_BOROUGH', 'CIVIC_PARTNER', 'URBAN_CORRIDORS', 'ACTIVE_MOBILITY'],
    website: 'https://montreal.ca/verdun',
    instagramUrl: 'https://www.instagram.com/arr_verdun',
  }
];

export const SPONSORS: Sponsor[] = [
  {
    id: 'spon-rockin',
    name: 'ROCKIN\' FRAMES',
    image: '/sponsors/rockin.png',
    website: 'https://rockinframes.com',
  },
  {
    id: 'spon-solo',
    name: 'Boutique Solo-Inline',
    image: '/sponsors/solo.png',
    website: 'https://solo-inline.com/'
  },
  {
    id: 'spon-lowlife',
    name: 'Lowlife Mtl',
    image: '/sponsors/lowlife.png',
    website: 'https://www.lowlifemtl.com/'
  },
  {
    id: 'spon-skpro',
    name: 'SkatePro',
    image: '/sponsors/skatepro.png',
    website: 'https://www.skatepro.ca/'
  },
  {
    id: 'spon-prosk8place',
    name: 'ProSkaters Place',
    image: '/sponsors/proskaterplace.png',
    website: 'https://proskatersplace.ca/'
  },
  {
    id: 'spon-flyingeagle',
    name: 'FlyingEagle Skate',
    image: '/sponsors/flyingeagle.png',
    website: 'https://www.flyingeagleskates.com/'
  },
  {
    id: 'spon-yoyo',
    name: 'YOYOSKATE',
    image: '/sponsors/yoyo.png',
    website: 'https://www.yoyoskateofficial.com/'
  }
];

export const TIMETABLE_EVENTS: TimetableEvent[] = [
  // Day 1 - Friday, Sept 11
  {
    id: 'time-d1-1',
    title: {
      EN: 'Urban Street Ride 20km',
      FR: 'Randonnée urbaine 20kms',
      ES: 'Ruta Urbana de 20 km',
    },
    description: {
      EN: 'Easy scenic ride along the waterfront, passing by the LaSalle skatepark and pumptrack; by Rolling Tribes.',
      FR: 'Randonnée tranquille le long de l’eau, en passant par le skatepark et pumptrack de LaSalle ; par Rolling Tribes.',
      ES: 'Paseo tranquilo junto al agua, pasando por el skatepark y pumptrack de LaSalle; por Rolling Tribes.',
    },
    longDescription: {
      EN: 'A scenic and relaxed 20km group roll along the waterfront of Montreal, routing through LaSalle skatepark and the local pumptrack. Led and escorted by the Rolling Tribes crew.',
      FR: 'Randonnée tranquille de 20 km le long de l’eau, en passant par le skatepark et pumptrack de LaSalle ; organisée et encadrée par Rolling Tribes.',
      ES: 'Recorrido panorámico y tranquilo de 20 km junto a la orilla del agua, pasando por el skatepark y pumptrack de LaSalle; organizado y guiado por Rolling Tribes.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '10:00 - 12:00',
    level: 'intermediate',
    startLocation: {
      EN: 'Parc du Souvenir (Verdun Metro)',
      FR: 'Parc du Souvenir (Métro Verdun)',
      ES: 'Parc du Souvenir (Metro Verdun)',
    },
    endLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    category: {
      EN: 'Street Ride',
      FR: 'Randonnée Urbaine',
      ES: 'Ruta Urbana',
    },
    type: 'ride',
    day: 1,
    iconName: 'directions_bike',
  },
  {
    id: 'time-d1-2',
    title: {
      EN: 'Open Skate & Warm-Up',
      FR: 'Patinage libre',
      ES: 'Patinaje Libre y Calentamiento',
    },
    description: {
      EN: 'Setup, open skating, and warm-up session.',
      FR: 'Mise en place et échauffement.',
      ES: 'Puesta en marcha y calentamiento.',
    },
    longDescription: {
      EN: 'Free open skating session at the rink to warm up, dial in your frames, test gear, and meet the community before the workshops begin.',
      FR: 'Session de patinage libre pour s\'échauffer, tester son matériel, ajuster ses platines et se retrouver avant le début des ateliers.',
      ES: 'Sesión de patinaje libre en la pista para calentar, ajustar patines y compartir con la comunidad antes del inicio de los talleres.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzIYd8nyAicsDj0p9QMw0vc_OypY39Qi03q0N_nV2O9EkC9DmBiDS8VszGJGjdHD-Q7d01ywp0A6xGw1wqhRZnXfdWLJ7oDHSdPCDdacR6jox0ay6ByqcF0vqzVhG1U8N5QEOvUDL_kM1tdY-B4oTeUMUJk9bp_aUq1t407HctiUyKcpMOuhxJJcu9j-sFO1rDOgw3Ts73e8m-CiwhsK9C9-xMAS0iDUgpnTPFewCZ6D1H0a-IVUfa',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '13:00 - 14:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Open Skate',
      FR: 'Patinage libre',
      ES: 'Patinaje libre',
    },
    type: 'social',
    day: 1,
    iconName: 'sparkles',
  },
  {
    id: 'time-d1-3',
    title: {
      EN: 'Skate Technique Masterclass with VRL',
      FR: 'Techniques de patin avec VRL',
      ES: 'Técnicas de Patinaje con VRL',
    },
    description: {
      EN: 'Mathieu Way and Pierra Vernex from VRL Speed Skating Club share a championship speed training session. Bring shoes and helmet.',
      FR: 'Mathieu Way et Pierra Vernex du club de patin VRL partagent une séance de leur entrainement de champion de patinage de vitesse. Apportez chaussures et casque.',
      ES: 'Mathieu Way y Pierra Vernex del club de patinaje VRL comparten una sesión de su entrenamiento de campeones de patinaje de velocidad. Trae calzado deportivo y casco.',
    },
    longDescription: {
      EN: 'Learn elite speed skating dynamics, stride mechanics, pushing efficiency, and edge control from champions Mathieu Way and Pierra Vernex of the VRL club. Please bring sneakers/running shoes for dryland prep and a helmet.',
      FR: 'Mathieu Way et Pierra Vernex du club de patin VRL partagent une séance de leur entrainement de champion de patinage de vitesse : technique de poussée, virages et contrôle des carres. Apportez chaussures de sport et casque.',
      ES: 'Aprende biomecánica de empuje, técnica de zancada y control de cantos con los campeones Mathieu Way y Pierra Vernex del club VRL. Por favor trae zapatillas deportivas para calentamiento en seco y casco.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '14:00 - 16:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 1,
    iconName: 'school',
  },
  {
    id: 'time-d1-4',
    title: {
      EN: 'Ça SLALOM! Freestyle Workshop',
      FR: 'Ça SLALOM !',
      ES: '¡Ça SLALOM! Taller de Freestyle',
    },
    description: {
      EN: 'Instruction in basic and advanced slalom tricks and cone flows, coached by Karen and Kaia from Rolling Tribes.',
      FR: 'Enseignement de figures de slalom basiques et avancées, encadré par Karen et Kaia de Rolling Tribes.',
      ES: 'Enseñanza de trucos de slalom básicos y avanzados, guiado por Karen y Kaia de Rolling Tribes.',
    },
    longDescription: {
      EN: 'From your first fish and snake cone runs to advanced footwork and spins, Karen and Kaia from Rolling Tribes break down freestyle cone technique step-by-step.',
      FR: 'Des premières passes aux figures avancées et combos autour des cônes, Karen et Kaia de Rolling Tribes décomposent les mouvements de slalom étape par étape.',
      ES: 'Desde las primeras líneas de conos hasta combinaciones y giros avanzados, Karen y Kaia de Rolling Tribes te enseñan técnicas de freestyle slalom paso a paso.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzIYd8nyAicsDj0p9QMw0vc_OypY39Qi03q0N_nV2O9EkC9DmBiDS8VszGJGjdHD-Q7d01ywp0A6xGw1wqhRZnXfdWLJ7oDHSdPCDdacR6jox0ay6ByqcF0vqzVhG1U8N5QEOvUDL_kM1tdY-B4oTeUMUJk9bp_aUq1t407HctiUyKcpMOuhxJJcu9j-sFO1rDOgw3Ts73e8m-CiwhsK9C9-xMAS0iDUgpnTPFewCZ6D1H0a-IVUfa',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '16:00 - 17:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 1,
    iconName: 'brush',
  },
  {
    id: 'time-d1-5',
    title: {
      EN: 'WIZARD Skating Workshop',
      FR: 'Atelier de patinage WIZARD',
      ES: 'Taller de Patinaje WIZARD',
    },
    description: {
      EN: 'Instruction in Wizard style movement, rocker edge flow, and combos, coached by Seb from Rolling Tribes.',
      FR: 'Enseignement de mouvements et combos du style Wizard, encadré par Seb de Rolling Tribes.',
      ES: 'Enseñanza de movimientos y combinaciones del estilo Wizard, guiado por Seb de Rolling Tribes.',
    },
    longDescription: {
      EN: 'Discover the flow, Gazelle transitions, and rockered frame carving dynamics of Wizard skating. Seb from Rolling Tribes guides beginners through foundational weight distribution and fluid body turns.',
      FR: 'Découvrez la fluidité, les transitions Gazelle et les appuis sur platines rockered propres au patinage Wizard. Seb de Rolling Tribes guide les débutants sur les transferts de poids et les rotations du corps.',
      ES: 'Descubre la fluidez, transiciones Gazelle y tallado con guías rockered del patinaje estilo Wizard. Seb de Rolling Tribes guía a principiantes en distribución de peso y giros fluidos.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '17:00 - 18:00',
    level: 'beginner',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 1,
    iconName: 'school',
  },
  {
    id: 'time-d1-6',
    title: {
      EN: 'Skate Games & Fun Challenges',
      FR: 'Jeux',
      ES: 'Juegos y Desafíos en Patines',
    },
    description: {
      EN: 'Various fun skating games, agility challenges, and friendly community activities.',
      FR: 'Différents jeux et défis ludiques sur patins.',
      ES: 'Diferentes juegos divertidos y retos de agilidad sobre ruedas.',
    },
    longDescription: {
      EN: 'Fun community games and agility challenges on wheels for all participants. Great laughs, prize giveaways, and friendly energy.',
      FR: 'Jeux collectifs amusants et défis d\'agilité sur roulettes pour tous les participants. Bonne humeur et ambiance festive garanties.',
      ES: 'Juegos comunitarios divertidos y desafíos de agilidad sobre patines para todos los participantes. Risas, premios y excelente ambiente.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzIYd8nyAicsDj0p9QMw0vc_OypY39Qi03q0N_nV2O9EkC9DmBiDS8VszGJGjdHD-Q7d01ywp0A6xGw1wqhRZnXfdWLJ7oDHSdPCDdacR6jox0ay6ByqcF0vqzVhG1U8N5QEOvUDL_kM1tdY-B4oTeUMUJk9bp_aUq1t407HctiUyKcpMOuhxJJcu9j-sFO1rDOgw3Ts73e8m-CiwhsK9C9-xMAS0iDUgpnTPFewCZ6D1H0a-IVUfa',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '18:00 - 19:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Games',
      FR: 'Jeux',
      ES: 'Juegos',
    },
    type: 'social',
    day: 1,
    iconName: 'trophy',
  },
  {
    id: 'time-d1-7',
    title: {
      EN: 'Tranquille à Roulettes (Roller Disco)',
      FR: 'Tranquille à roulettes',
      ES: 'Tranquille à Roulettes (Roller Disco)',
    },
    description: {
      EN: 'Groove to Patins Platines (DJ Arielle Roberge) with dance moves by Marly. Free admission, with skate & gear rental on-site if needed.',
      FR: 'Vibre au rythme de Patins Platines (DJ Arielle Roberge) avec les moves de Marly. Accès gratuit et location de patins et protections sur place si besoin.',
      ES: 'Disfruta al ritmo de Patins Platines (DJ Arielle Roberge) con los pasos de baile de Marly. Acceso gratuito y alquiler de patines y protecciones en el lugar si se requiere.',
    },
    longDescription: {
      EN: 'The signature Montreal roller disco night on the heart of Esplanade Tranquille. Dance and skate under city lights with DJ Arielle Roberge (Patins Platines) and dance leader Marly. Free entrance for all, with on-site skate and protective gear rental available.',
      FR: 'La soirée roller disco incontournable au cœur de l\'Esplanade Tranquille. Dansez et patinez sous les lumières urbaines au son de Patins Platines (DJ Arielle Roberge) et des chorégraphies de Marly. Entrée gratuite, location de patins et équipements disponible sur place.',
      ES: 'La noche imperdible de roller disco en el corazón de la Esplanade Tranquille. Baila y patina bajo las luces de la ciudad con DJ Arielle Roberge (Patins Platines) y las coreografías de Marly. Entrada gratuita con alquiler de patines y protecciones disponible.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBk23iiPsQondimS8L4yxRofJ4bhsP047QTlBPD9Q2yAq81d3NVWmJPkMoTr-538WC-BYjgSUwL2KujXsd86RSSIWoIUPFWDCjC5znhkqE4sNF6ERE4RBrz1NAHjpvdYcCzVPhl3-Zxr86kRXEL4pew3b0hF0wcEmcXlS-W5jMlp00OGwHKc4tUvXNDcF2u6iZERWETMLoSwYmpfSpLYCqlrL4J03o2ZyXAxyJT3Z-l3270gFsqfT5g',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '19:00 - 23:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Esplanade Tranquille (Quartier des Spectacles)',
      FR: 'Esplanade Tranquille (Quartier des spectacles)',
      ES: 'Esplanade Tranquille (Quartier des spectacles)',
    },
    endLocation: undefined,
    category: {
      EN: 'Roller Disco',
      FR: 'Roller disco',
      ES: 'Roller disco',
    },
    type: 'social',
    day: 1,
    iconName: 'sparkles',
  },
  {
    id: 'time-d1-8',
    title: {
      EN: 'Light Up the 514: MTL ROLL Special (Outbound)',
      FR: 'Illumine le 514 : Spécial MTL ROLL (Aller)',
      ES: 'Ilumina el 514: Especial MTL ROLL (Ida)',
    },
    description: {
      EN: 'Join Rolling Tribes\' famous illuminated night ride with lights & music through downtown & the Old Port, arriving at Esplanade Tranquille for the final roller disco hour.',
      FR: 'Participe à la fameuse randonnée nocturne de Rolling Tribes toute en lumière et en musique, et visite le centre ville ainsi que le vieux port, pour arriver à l\'esplanade tranquille et profiter de la derniere heure de roller disco.',
      ES: 'Participa en la famosa ruta nocturna de Rolling Tribes con luces y música por el centro y el Puerto Viejo, llegando a la Esplanade Tranquille para la última hora de roller disco.',
    },
    longDescription: {
      EN: 'Join Rolling Tribes for the celebrated "Illumine le 514" night cruise. Bedecked in glowing neon LED arrays and rolling sound systems, we carve through Verdun, downtown Montreal, and the historic Old Port, rolling right onto Esplanade Tranquille to catch the climactic finale of the roller disco.',
      FR: 'Rejoignez la célèbre randonnée nocturne "Illumine le 514" de Rolling Tribes. Équipés de lumières et d\'enceintes mobiles, nous sillonnons Verdun, le centre-ville et le Vieux-Port pour débarquer sur l\'Esplanade Tranquille et savourer la dernière heure de roller disco.',
      ES: 'Únete a la emblemática ruta nocturna "Illumine le 514" de Rolling Tribes. Equipados con luces y música móvil, recorremos Verdun, el centro y el Puerto Viejo hasta llegar a la Esplanade Tranquille para disfrutar del gran final del roller disco.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '20:30 - 22:00',
    level: 'intermediate',
    startLocation: {
      EN: 'Parc du Souvenir (Verdun Metro)',
      FR: 'Parc du Souvenir (Métro Verdun)',
      ES: 'Parc du Souvenir (Metro Verdun)',
    },
    endLocation: {
      EN: 'Esplanade Tranquille (Quartier des Spectacles)',
      FR: 'Esplanade Tranquille (Quartier des spectacles)',
      ES: 'Esplanade Tranquille (Quartier des spectacles)',
    },
    category: {
      EN: 'Street Ride',
      FR: 'Randonnée Urbaine',
      ES: 'Ruta Urbana',
    },
    type: 'ride',
    day: 1,
    iconName: 'directions_bike',
  },
  {
    id: 'time-d1-9',
    title: {
      EN: 'Light Up the 514: MTL ROLL Special (Return)',
      FR: 'Illumine le 514 : Spécial MTL ROLL (Retour)',
      ES: 'Ilumina el 514: Especial MTL ROLL (Regreso)',
    },
    description: {
      EN: 'An easy-paced night return cruise on skates back to Verdun Metro for anyone wanting to roll home together.',
      FR: 'On rentre tranquillement jusqu\'au métro Verdun en patin, pour celles et ceux qui en ont envie.',
      ES: 'Regreso tranquilo sobre patines hasta la estación de metro Verdun para quienes deseen volver en grupo.',
    },
    longDescription: {
      EN: 'A friendly, relaxed group night ride rolling back from Esplanade Tranquille through quiet midnight streets to Verdun Metro. The perfect end to Day 1.',
      FR: 'Randonnée de retour nocturne conviviale et détendue depuis l\'Esplanade Tranquille à travers les rues calmes jusqu\'au métro Verdun. La conclusion idéale du Jour 1.',
      ES: 'Recorrido nocturno grupal tranquilo y amigable desde la Esplanade Tranquille por calles nocturnas hasta el metro Verdun. El cierre perfecto para el Día 1.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBk23iiPsQondimS8L4yxRofJ4bhsP047QTlBPD9Q2yAq81d3NVWmJPkMoTr-538WC-BYjgSUwL2KujXsd86RSSIWoIUPFWDCjC5znhkqE4sNF6ERE4RBrz1NAHjpvdYcCzVPhl3-Zxr86kRXEL4pew3b0hF0wcEmcXlS-W5jMlp00OGwHKc4tUvXNDcF2u6iZERWETMLoSwYmpfSpLYCqlrL4J03o2ZyXAxyJT3Z-l3270gFsqfT5g',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '23:15 - 23:59',
    level: 'intermediate',
    startLocation: {
      EN: 'Esplanade Tranquille (Quartier des Spectacles)',
      FR: 'Esplanade Tranquille (Quartier des spectacles)',
      ES: 'Esplanade Tranquille (Quartier des spectacles)',
    },
    endLocation: {
      EN: 'Parc du Souvenir (Verdun Metro)',
      FR: 'Parc du Souvenir (Métro Verdun)',
      ES: 'Parc du Souvenir (Metro Verdun)',
    },
    category: {
      EN: 'Street Ride',
      FR: 'Randonnée Urbaine',
      ES: 'Ruta Urbana',
    },
    type: 'ride',
    day: 1,
    iconName: 'directions_bike',
  },

  // Day 2 - Saturday, Sept 12
  {
    id: 'time-d2-1',
    title: {
      EN: 'Slalom Masterclass & Qualifications',
      FR: 'Masterclass de Slalom & Qualifications',
      ES: 'Clase Magistral de Slalom y Clasificación',
    },
    description: {
      EN: 'Agility tests and qualification trials. Watch speed-slalom and freestyle riders clear cones at high tempo.',
      FR: 'Épreuves d\'agilité et de qualification. Démonstrations de speed-slalom et freestyle autour des cônes.',
      ES: 'Pruebas de agilidad y clasificación. Exhibición de speed-slalom y estilo libre entre conos.',
    },
    longDescription: {
      EN: 'For precision masters and spectators alike. We construct a technical cone grid where competitors showcase speed-slalom, classic freestyle, and battle slalom. Master-class coaching sessions are held prior to the tournament.',
      FR: 'Pour les passionnés de précision et le public. Grille technique de cônes avec épreuves de slalom vitesse, freestyle classique et battle, précédées d\'ateliers de perfectionnement.',
      ES: 'Para expertos en precisión y espectadores. Circuito técnico de conos con pruebas de speed slalom, freestyle y batallas, con talleres guiados por profesionales.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD-_Ict4THRYVHUB8CLRsQjgip0_D30ZyoyF3yuGBHdka_2AoHhMmS9U6mAhb27nWMMs3BBRNqfKVwy6kfq8sz8PmtLkrxyWtaPp4TSQBSk7UMiNpERlxI8-680gry-LjbhUsgZUsqRaHxzTfrRQ6-yh7DOA76n1FMmzJeTY_J-CRZF08Ei8v6bewiMx3ZrF2rSd7FLtZ9MoNHkbLYjc_bqWQis-tSHZlQWJyvXG7ejVkQfcMDwSu2J',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '11:00 - 13:00',
    level: 'beginner',
    startLocation: {
      EN: 'Verdun Arena Court',
      FR: 'Cour de l\'Aréna de Verdun',
      ES: 'Pista del Arena de Verdun',
    },
    endLocation: undefined,
    category: {
      EN: 'Competition',
      FR: 'Compétition',
      ES: 'Competición',
    },
    type: 'competition',
    day: 2,
    iconName: 'timeline',
  },
  {
    id: 'time-d2-2',
    title: {
      EN: 'Street Murals Art Crawl Ride',
      FR: 'Randonnée Découverte des Murales Urbaines',
      ES: 'Ruta de Arte Urbano y Murales',
    },
    description: {
      EN: 'Moderate paced scenic ride through Mile End and Plateau, guided by street artists. High-fidelity photo-ops.',
      FR: 'Parcours à allure modérée à travers le Mile End et le Plateau, commenté par des artistes urbains.',
      ES: 'Paseo panorámico a ritmo moderado por Mile End y Plateau, guiado por artistas urbanos.',
    },
    longDescription: {
      EN: 'Explore the legendary street murals of Montreal. This slow-to-moderate paced ride takes you through Saint-Laurent and Mile End back alleys, detailing the history of the city’s underground art scene and culminating in an outdoor gallery social.',
      FR: 'Explorez les célèbres murales de Montréal. Cette randonnée accessible traverse les ruelles du Mile End et du Plateau avec arrêts photos et anecdotes sur la scène artistique locale.',
      ES: 'Explora los murales urbanos de Montreal. Recorrido a velocidad moderada por callejones de Saint-Laurent y Mile End con paradas fotográficas.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBo4OsmywxyzTBGMpyJ2bONw_D0vlGKtLZIUtQ4wCtoFmboYAd8JRtC56FQUMeY8x9V8dzM_NfKPZx3nWcaZ-Sl4MOCRIbSLJQWf2iyqQohqSR3A_ehGXIy2s8JKHmB3JdIyFoQFP6DRGkHWg8OZCF8NMnXp-wK4XDzjSuww4NIBVKO79hSU39GeE8hzJPDSmXzxEfLubeML19YdskJ-qsNR1-1XIFxYW_ZjYVFVuti1sqlSA6uLIU0',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '14:00 - 16:00',
    level: 'beginner',
    startLocation: {
      EN: 'Saint-Laurent Metro Station',
      FR: 'Station de métro Saint-Laurent',
      ES: 'Estación de metro Saint-Laurent',
    },
    endLocation: {
      EN: 'Mile End Skate Plaza (Van Horne)',
      FR: 'Plaza Skate Mile End (Sous le viaduc Van Horne)',
      ES: 'Plaza Skate Mile End (Bajo el viaducto Van Horne)',
    },
    category: {
      EN: 'Rides',
      FR: 'Randonnées',
      ES: 'Rutas',
    },
    type: 'ride',
    day: 2,
    iconName: 'brush',
  },
  {
    id: 'time-d2-3',
    title: {
      EN: 'Wizard Flow & Carving Workshop',
      FR: 'Atelier Wizard Skating & Fluidité',
      ES: 'Taller de Wizard Skating y Giros Fluidos',
    },
    description: {
      EN: 'A dedicated session for edge-flow, transitions, flatland carving, gazelles, and swivel patterns.',
      FR: 'Session axée sur les carres, transitions au sol, virages fluides, gazelles et pivots.',
      ES: 'Sesión dedicada a control de cantos, transiciones fluidas, figuras planas y giros estilo wizard.',
    },
    longDescription: {
      EN: 'Explore flatland artistry. Led by style pioneers, this session teaches wizard-style movements, swivels, gazelles, lions, and artistic carve combinations. Perfect for those with multi-rockered long frames looking to unlock flow state.',
      FR: 'Perfectionnez votre style sur le plat. Encadré par des riders experts, cet atelier aborde les pivots, gazelles, lions et enchaînements artistiques pour libérer votre fluidité.',
      ES: 'Descubre el arte sobre ruedas. Guiado por patinadores expertos, este taller enseña movimientos estilo wizard, giros, gazelles y combinaciones artísticas continuas.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGtm6jK2gS9pavNm6jz5SH78XNkpBRlByAo36kawzTStCMCJWYmZDHSmFxJA65lvTw8t7zt04GLIQyw1RzK2wuO05f9ZUaAlWtvbO0aBn3eJYWya9H6nsp3DxS7hNByQEjXU3KTQwIMIXkc0poEBPheC_ZLEE9T_YNzd8qje1-WGGFqKJmuIpyaCUb_hfOnjQh6gB6tvT__tk1NoJ2zBkZsKku1Z9MZ1hdAsg0SCfd8F8nraYwsNCR',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '16:30 - 18:00',
    level: 'beginner',
    startLocation: {
      EN: 'Verdun Waterfront Plaza',
      FR: 'Plaza des Berges de Verdun',
      ES: 'Plaza Costera de Verdun',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 2,
    iconName: 'auto_awesome',
  },
  {
    id: 'time-d2-4',
    title: {
      EN: 'Night Mass Ride: Chapter II',
      FR: 'Grande Randonnée Nocturne : Chapitre II',
      ES: 'Gran Ruta Nocturna: Capítulo II',
    },
    description: {
      EN: 'Higher intensity route crossing into Montreal Downtown boulevards. Experience maximum neon illumination.',
      FR: 'Itinéraire dynamique au cœur des grands boulevards du centre-ville de Montréal sous les lumières.',
      ES: 'Recorrido dinámico en el centro de Montreal, con velocidad y máxima iluminación urbana.',
    },
    longDescription: {
      EN: 'The flagship Saturday Night Mass Ride. An extended, high-intensity route crossing through the heart of downtown Montreal, illuminated bridges, and grand boulevard sprints.',
      FR: 'La randonnée majeure du samedi soir. Parcours étendu à bonne cadence traversant le cœur du centre-ville, les ponts illuminés et les grandes artères urbaines.',
      ES: 'La ruta estrella del sábado por la noche. Recorrido amplio y enérgico cruzando el centro de Montreal, puentes iluminados y avenidas principales.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '20:00 - 22:30',
    level: 'intermediate',
    startLocation: {
      EN: 'Verdun Waterfront Plaza',
      FR: 'Plaza des Berges de Verdun',
      ES: 'Plaza Costera de Verdun',
    },
    endLocation: {
      EN: 'Place des Festivals (Quartier des Spectacles)',
      FR: 'Place des Festivals (Quartier des Spectacles)',
      ES: 'Place des Festivals (Quartier des Spectacles)',
    },
    category: {
      EN: 'Prime Event',
      FR: 'Événement Phare',
      ES: 'Evento Principal',
    },
    type: 'ride',
    day: 2,
    iconName: 'directions_bike',
  },
  {
    id: 'time-d2-5',
    title: {
      EN: 'Syndicate Afterparty: Bass Drop',
      FR: 'Soirée Syndicate : Bass & Rythmes',
      ES: 'Fiesta Syndicate: Noche de Ritmo y Baile',
    },
    description: {
      EN: 'The absolute pinnacle celebration with electronic music sets, visual mapping, and skate community vibes.',
      FR: 'Célébration festive avec musique électronique, projections visuelles et ambiance rassembleuse.',
      ES: 'Gran fiesta con DJs de música electrónica, proyecciones visuales y celebración comunitaria.',
    },
    longDescription: {
      EN: 'When the wheels stop rolling, the bass drops. An exclusive celebration for registered participants featuring guest DJs, lighting installations, and celebration zones.',
      FR: 'Après la rando, place à la musique et à la fête. Célébration réservée aux participants avec DJs invités, éclairages festifs et espaces détente.',
      ES: 'Al terminar la ruta sobre ruedas, comienza la fiesta. Encuentro exclusivo con DJs, instalaciones de iluminación y zona de baile.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzIYd8nyAicsDj0p9QMw0vc_OypY39Qi03q0N_nV2O9EkC9DmBiDS8VszGJGjdHD-Q7d01ywp0A6xGw1wqhRZnXfdWLJ7oDHSdPCDdacR6jox0ay6ByqcF0vqzVhG1U8N5QEOvUDL_kM1tdY-B4oTeUMUJk9bp_aUq1t407HctiUyKcpMOuhxJJcu9j-sFO1rDOgw3Ts73e8m-CiwhsK9C9-xMAS0iDUgpnTPFewCZ6D1H0a-IVUfa',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '22:30 - 03:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Warehouse Vector B (Downtown Hub)',
      FR: 'Entrepôt Vecteur B (Centre-Ville)',
      ES: 'Almacén Vector B (Centro)',
    },
    endLocation: undefined,
    category: {
      EN: 'Social',
      FR: 'Rassemblement',
      ES: 'Social',
    },
    type: 'social',
    day: 2,
    iconName: 'sparkles',
  },

  // Day 3 - Sunday, Sept 13
  {
    id: 'time-d3-1',
    title: {
      EN: 'Lachine Canal 50K Marathon',
      FR: 'Marathon 50K du Canal de Lachine',
      ES: 'Maratón 50K del Canal de Lachine',
    },
    description: {
      EN: 'The supreme endurance challenge. Draft lines, pace groups, and sprint checkpoints across 50 kilometers.',
      FR: 'Le défi d\'endurance ultime. Lignes de drafting, groupes d\'allure et points de passage sur 50 km.',
      ES: 'El reto supremo de resistencia. Grupos de ritmo, relevos y control de velocidad a lo largo de 50 km.',
    },
    longDescription: {
      EN: 'A test of stamina and technique. This 50km circuit runs along Montreal’s scenic Lachine Canal paths and outer port areas. Designed for endurance skaters who love drafting and continuous pace.',
      FR: 'Un test d\'endurance et de technique le long du canal de Lachine. Conçu pour les patineurs appréciant la vitesse de croisière et le travail en peloton.',
      ES: 'Prueba de resistencia y velocidad por las orillas del Canal de Lachine. Ideal para patinadores que disfrutan del ritmo constante y el trabajo en pelotón.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBtwBSh3I9965A5VA97GMNT6WPcpuu5lY8I0IjGiK64Fk0WHYIT5lLoUPqdrAuZgT135nCSSYXNEfdmjHaaTmCSimZFNPGifGOgEHqV9Ce7EiT2ka47xYp-GUeXAz7mZOk50o73irbImltxqiiVP2kW6I3JS43Y4XX4P68mZoG07MBWF4_BVlxnFnuICCFniVFHWu74Nsja97XezTH6yQTaucqy6wP_2Gzi8Ppx8r-LeFXGjoDfCTB8',
    date: {
      EN: 'Sunday, Sept 13, 2026',
      FR: 'Dimanche 13 sept. 2026',
      ES: 'Domingo 13 sept. 2026',
    },
    time: '09:00 - 12:30',
    level: 'advanced',
    startLocation: {
      EN: 'Lachine Canal Lock 1 (Old Port)',
      FR: 'Écluse no 1 du Canal de Lachine (Vieux-Port)',
      ES: 'Esclusa 1 del Canal de Lachine (Puerto Viejo)',
    },
    endLocation: {
      EN: 'Lachine Lighthouse Park',
      FR: 'Parc du Phare de Lachine',
      ES: 'Parque del Faro de Lachine',
    },
    category: {
      EN: 'Rides',
      FR: 'Randonnées',
      ES: 'Rutas',
    },
    type: 'ride',
    day: 3,
    iconName: 'route',
  },
  {
    id: 'time-d3-2',
    title: {
      EN: 'Braking & Downhill Mastery Workshop',
      FR: 'Atelier Freinage & Maîtrise des Descentes',
      ES: 'Taller de Frenado y Control en Pendientes',
    },
    description: {
      EN: 'Advanced stopping methods (Magic Slide, Soul Slide, Powerslide) and downhill speed control techniques.',
      FR: 'Techniques d\'arrêt avancées (Magic Slide, Soul Slide, Powerslide) et contrôle de vitesse en pente.',
      ES: 'Técnicas avanzadas de frenado (Magic Slide, Soul Slide, Powerslide) y control en descensos.',
    },
    longDescription: {
      EN: 'Learn advanced stopping and downhill control techniques from expert instructors: Magic Slide, Soul Slide, Powerslide variations, carving turns, and safe speed reduction on inclines.',
      FR: 'Apprenez les techniques de freinage et de contrôle en pente avec des entraîneurs d\'expérience : Magic Slide, Soul Slide, Powerslide et virages pour ralentir en toute confiance.',
      ES: 'Aprende métodos de frenado seguro y control de descensos con instructores certificados: Magic Slide, Soul Slide, Powerslide y virajes progresivos.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGtm6jK2gS9pavNm6jz5SH78XNkpBRlByAo36kawzTStCMCJWYmZDHSmFxJA65lvTw8t7zt04GLIQyw1RzK2wuO05f9ZUaAlWtvbO0aBn3eJYWya9H6nsp3DxS7hNByQEjXU3KTQwIMIXkc0poEBPheC_ZLEE9T_YNzd8qje1-WGGFqKJmuIpyaCUb_hfOnjQh6gB6tvT__tk1NoJ2zBkZsKku1Z9MZ1hdAsg0SCfd8F8nraYwsNCR',
    date: {
      EN: 'Sunday, Sept 13, 2026',
      FR: 'Dimanche 13 sept. 2026',
      ES: 'Domingo 13 sept. 2026',
    },
    time: '13:00 - 14:30',
    level: 'intermediate',
    startLocation: {
      EN: 'Verdun Riverside Slope Area',
      FR: 'Zone en pente des Berges de Verdun',
      ES: 'Área inclinada de la Ribera de Verdun',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 3,
    iconName: 'school',
  },
  {
    id: 'time-d3-3',
    title: {
      EN: 'High-Jump & Ramp Battle',
      FR: 'Compétition Saut en Hauteur & Modules',
      ES: 'Competencia de Salto de Altura y Rampa',
    },
    description: {
      EN: 'Clear the bar. Spectacular ramp launches, free jump height battles, and style tricks judged by guest pros.',
      FR: 'Passez la barre. Sauts spectaculaires avec tremplin, saut libre en hauteur et figures de style.',
      ES: 'Supera el listón. Impresionantes saltos de rampa, salto libre de altura y trucos evaluados por jueces invitados.',
    },
    longDescription: {
      EN: 'Gravity-defying action on the waterfront. Using certified launch ramps and adjustable high bars, competitors battle for maximum height (Free Jump) and trick style over obstacles.',
      FR: 'Action aérienne sur les berges. Avec tremplins homologués et barres ajustables, les patineurs s\'affrontent en saut libre de hauteur et démonstration de style.',
      ES: 'Acción acrobática junto al río. Con rampas diseñadas y barras regulables, los participantes compiten por la mayor altura (Free Jump) y trucos con estilo.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAcz5koXIDour-9seud2hMpfMyL-_igvkj8j03j20Zl82np7JbR2LTnhd6xlbVKwvbU9LsACykPpKen2VtNbc5FFrl72JyV5zULmrPzmprHSN6Xz5ZsIqK2Ru3HsHTdGaxGLUb8tsP56qQHAuvq9_jEyWiVxo4BIY6rwuwUL2WbKOn3x-9b94cTQj63E3Al0yVXhOMHS3d0ujSQfuGQf_FhLbd1NYV5vjJMu7TSfeZwWXMuIYwWhj8T',
    date: {
      EN: 'Sunday, Sept 13, 2026',
      FR: 'Dimanche 13 sept. 2026',
      ES: 'Domingo 13 sept. 2026',
    },
    time: '15:00 - 18:00',
    level: 'advanced',
    startLocation: {
      EN: 'Verdun Pump Track & Jump Hub',
      FR: 'Pumptrack et Module Saut de Verdun',
      ES: 'Pumptrack y Módulo de Salto de Verdun',
    },
    endLocation: undefined,
    category: {
      EN: 'Competition',
      FR: 'Compétition',
      ES: 'Competición',
    },
    type: 'competition',
    day: 3,
    iconName: 'flight_takeoff',
  },
  {
    id: 'time-d3-4',
    title: {
      EN: 'Grid Closing Awards & Social',
      FR: 'Remise des Prix & Cérémonie de Clôture',
      ES: 'Premiación y Ceremonia de Clausura',
    },
    description: {
      EN: 'Podium awards for Slalom, Marathon, and Jump. Crowning of MTL ROLL 2026 champions. Final celebration.',
      FR: 'Podiums et récompenses pour le Slalom, le Marathon et le Saut. Célébration de clôture MTL ROLL 2026.',
      ES: 'Podio y entrega de premios para Slalom, Maratón y Salto. Celebración final de MTL ROLL 2026.',
    },
    longDescription: {
      EN: 'Official closing ceremony and podium awards for Slalom, Marathon, and Jump competitions. Crowning of MTL ROLL 2026 champions followed by a waterfront celebration.',
      FR: 'Cérémonie officielle de clôture et remise des médailles pour les compétitions. Célébration conviviale au bord de l\'eau pour terminer la fin de semaine en beauté.',
      ES: 'Ceremonia oficial de clausura y entrega de premios de las competencias de Slalom, Maratón y Salto, con fiesta final frente al río.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBk23iiPsQondimS8L4yxRofJ4bhsP047QTlBPD9Q2yAq81d3NVWmJPkMoTr-538WC-BYjgSUwL2KujXsd86RSSIWoIUPFWDCjC5znhkqE4sNF6ERE4RBrz1NAHjpvdYcCzVPhl3-Zxr86kRXEL4pew3b0hF0wcEmcXlS-W5jMlp00OGwHKc4tUvXNDcF2u6iZERWETMLoSwYmpfSpLYCqlrL4J03o2ZyXAxyJT3Z-l3270gFsqfT5g',
    date: {
      EN: 'Sunday, Sept 13, 2026',
      FR: 'Dimanche 13 sept. 2026',
      ES: 'Domingo 13 sept. 2026',
    },
    time: '18:30 - 20:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Verdun Waterfront Plaza',
      FR: 'Plaza des Berges de Verdun',
      ES: 'Plaza Costera de Verdun',
    },
    endLocation: undefined,
    category: {
      EN: 'Social',
      FR: 'Rassemblement',
      ES: 'Social',
    },
    type: 'social',
    day: 3,
    iconName: 'trophy',
  },
];
