import { Activity, Guest, Organizer, Sponsor, TimetableEvent } from './types';

export const ACTIVITIES: Activity[] = [
  {
    id: 'act-night-ride',
    title: 'Night Ride',
    category: 'Prime Event',
    description: 'The definitive MTL ROLL experience. A massive, synchronized assault on the city streets under the cover of darkness. High speeds, neon trails, and pure kinetic energy.',
    longDescription: 'The headline event of MTL ROLL 2026. Join over a thousand skaters as we take over Montreal’s high-velocity boulevards. Fully escorted by safety marshals, this synchronized ride spans across major downtown vectors with neon light installations and synchronized mobile sound systems.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    iconName: 'directions_bike', // Will map to Lucide icon Bike or Zap
    difficulty: 'All Levels',
    date: 'Friday & Saturday, Sept 11 & 12',
    time: '20:00 - 23:00',
    location: 'Starts at Verdun Grid Hub',
  },
  {
    id: 'act-mural-ride',
    title: 'Mural Ride',
    category: 'Rides',
    description: "A curated tour through Montreal's most iconic and hidden street art installations. Pace is moderate, visuals are maximum.",
    longDescription: "Explore the legendary street murals of Montreal. This slow-to-moderate paced ride takes you through Saint-Laurent and Mile End back alleys, detailing the history of the city’s underground art scene and culminating in an outdoor gallery social.",
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBo4OsmywxyzTBGMpyJ2bONw_D0vlGKtLZIUtQ4wCtoFmboYAd8JRtC56FQUMeY8x9V8dzM_NfKPZx3nWcaZ-Sl4MOCRIbSLJQWf2iyqQohqSR3A_ehGXIy2s8JKHmB3JdIyFoQFP6DRGkHWg8OZCF8NMnXp-wK4XDzjSuww4NIBVKO79hSU39GeE8hzJPDSmXzxEfLubeML19YdskJ-qsNR1-1XIFxYW_ZjYVFVuti1sqlSA6uLIU0',
    iconName: 'brush', // Lucide Brush / Palette
    difficulty: 'All Levels',
    date: 'Saturday, Sept 12',
    time: '14:00 - 17:00',
    location: 'Starts at Saint-Laurent Metro',
  },
  {
    id: 'act-long-distance',
    title: 'Long Distance',
    category: 'Rides',
    description: 'Test your endurance on a relentless 50km circuit. Strategic pacing and drafting are essential to survive the loop.',
    longDescription: 'A brutal test of mental and physical fortitude. This 50km circuit pushes you across Montreal’s scenic outer canal vectors and port areas. Perfect for marathon speed-skaters and long-frame inline enthusiasts who thrive on drafting and pace control.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBtwBSh3I9965A5VA97GMNT6WPcpuu5lY8I0IjGiK64Fk0WHYIT5lLoUPqdrAuZgT135nCSSYXNEfdmjHaaTmCSimZFNPGifGOgEHqV9Ce7EiT2ka47xYp-GUeXAz7mZOk50o73irbImltxqiiVP2kW6I3JS43Y4XX4P68mZoG07MBWF4_BVlxnFnuICCFniVFHWu74Nsja97XezTH6yQTaucqy6wP_2Gzi8Ppx8r-LeFXGjoDfCTB8',
    iconName: 'route', // Lucide Route / Milestone
    difficulty: 'Tech',
    date: 'Sunday, Sept 13',
    time: '09:00 - 12:00',
    location: 'Starts at Lachine Canal Grid',
  },
  {
    id: 'act-slalom',
    title: 'Slalom',
    category: 'Tech',
    description: 'Precision carving through tightly spaced cones. Requires maximum agility, technical edge control, and intense focus.',
    longDescription: 'For the precision masters. We construct a technical cone grid where competitors showcase speed-slalom, classic freestyle, and battle slalom. Master-class coaching sessions are also held prior to the tournament.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD-_Ict4THRYVHUB8CLRsQjgip0_D30ZyoyF3yuGBHdka_2AoHhMmS9U6mAhb27nWMMs3BBRNqfKVwy6kfq8sz8PmtLkrxyWtaPp4TSQBSk7UMiNpERlxI8-680gry-LjbhUsgZUsqRaHxzTfrRQ6-yh7DOA76n1FMmzJeTY_J-CRZF08Ei8v6bewiMx3ZrF2rSd7FLtZ9MoNHkbLYjc_bqWQis-tSHZlQWJyvXG7ejVkQfcMDwSu2J',
    iconName: 'timeline', // Lucide Sliders / Shuffle
    difficulty: 'Tech',
    date: 'Saturday, Sept 12',
    time: '11:00 - 13:00',
    location: 'Verdun Arena Court',
  },
  {
    id: 'act-jump',
    title: 'Jump',
    category: 'High Risk',
    description: 'Ramp launches and gap clears. Push your aerial limits in a controlled environment with expert spotters.',
    longDescription: 'High-flying gravity-defying action. Using bespoke wooden launch ramps and adjustable high bars, competitors battle for maximum height (Free Jump) and best style trick (High Jump) over simulated urban obstacles.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAcz5koXIDour-9seud2hMpfMyL-_igvkj8j03j20Zl82np7JbR2LTnhd6xlbVKwvbU9LsACykPpKen2VtNbc5FFrl72JyV5zULmrPzmprHSN6Xz5ZsIqK2Ru3HsHTdGaxGLUb8tsP56qQHAuvq9_jEyWiVxo4BIY6rwuwUL2WbKOn3x-9b94cTQj63E3Al0yVXhOMHS3d0ujSQfuGQf_FhLbd1NYV5vjJMu7TSfeZwWXMuIYwWhj8T',
    iconName: 'flight_takeoff', // Lucide TrendingUp / Rocket
    difficulty: 'High Risk',
    date: 'Sunday, Sept 13',
    time: '15:00 - 18:00',
    location: 'Verdun Outdoor Pump Circuit',
  },
  {
    id: 'act-wizard',
    title: 'Wizard',
    category: 'Style',
    description: 'Flow state skating. Link complex transitions, spins, and footwork on flat ground with long-frame setups.',
    longDescription: 'Explore flatland artistry. Led by style pioneers, this session teaches wizard-style movements, swivels, gazelles, lions, and artistic carve combinations. Perfect for those with multi-rockered long frames looking to unlock flow state.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGtm6jK2gS9pavNm6jz5SH78XNkpBRlByAo36kawzTStCMCJWYmZDHSmFxJA65lvTw8t7zt04GLIQyw1RzK2wuO05f9ZUaAlWtvbO0aBn3eJYWya9H6nsp3DxS7hNByQEjXU3KTQwIMIXkc0poEBPheC_ZLEE9T_YNzd8qje1-WGGFqKJmuIpyaCUb_hfOnjQh6gB6tvT__tk1NoJ2zBkZsKku1Z9MZ1hdAsg0SCfd8F8nraYwsNCR',
    iconName: 'auto_awesome', // Lucide Sparkles
    difficulty: 'Style',
    date: 'Saturday, Sept 12',
    time: '16:30 - 18:00',
    location: 'Verdun Waterfront Plaza',
  }
];

export const GUESTS: Guest[] = [
  {
    id: 'guest-dave',
    name: 'Dave',
    tags: ['PUMPTRACK'],
    image: '/guests/dave.jpg',
    instagramUrl: 'https://www.instagram.com/85pereira/',
  },
  {
    id: 'guest-melina',
    name: 'Melina',
    tags: ['PUMPTRACK'],
    image: '/guests/melina.jpg',
    instagramUrl: 'https://www.instagram.com/_melina_rc/',
  },
  {
    id: 'guest-seb',
    name: 'Seb',
    tags: ['JUMP', 'WIZARD', 'SPEAKER'],
    image: '/guests/seb.jpg',
    instagramUrl: 'https://www.instagram.com/sebl988/',
  },
  {
    id: 'guest-karen',
    name: 'Karen',
    tags: ['SLALOM'],
    image: '/guests/karen.jpg',
    instagramUrl: 'https://www.instagram.com/karenest9/',
  },
  {
    id: 'guest-kaia',
    name: 'Kaia',
    tags: ['SLALOM'],
    image: '/guests/kaia.png',
    instagramUrl: 'https://www.instagram.com/kaia_baird_/',
  },
  {
    id: 'guest-saul',
    name: 'Saul',
    tags: ['SLIDE'],
    image: '/guests/saul.jpg',
    instagramUrl: 'https://www.instagram.com/saul_gomez_lopez/',
  },
  {
    id: 'guest-xav',
    name: 'Xavier',
    tags: ['SKATEPARK'],
    image: '/guests/xavier.jpg',
    instagramUrl: 'https://www.instagram.com/crazyxav.art/',
  },
  {
    id: 'guest-emile',
    name: 'Émile',
    tags: ['FREESTYLE'],
    image: '/guests/emile.jpg',
    instagramUrl: 'https://www.instagram.com/emile_besh/',
  },
  {
    id: 'guest-marly',
    name: 'Marly',
    tags: ['ROLLER_DANCE'],
    image: '/guests/marly.jpg',
    instagramUrl: 'https://www.instagram.com/skatewithmarly/',
  },
  {
    id: 'guest-skatespace',
    name: 'SKATESPACE',
    tags: ['INTRO_TO_SKATING', 'ROLLER_DANCE', 'SLALOM', 'GAMES'],
    image: '/guests/skatespace.jpg',
    instagramUrl: 'https://www.instagram.com/skatespace.ca/',
  },
  {
    id: 'guest-vrl',
    name: 'VRL',
    tags: ['SPEED_SKATING'],
    image: '/guests/vrl.png',
    instagramUrl: 'https://www.instagram.com/vrlroller/',
  },
];

export const ORGANIZERS: Organizer[] = [
  {
    id: 'org-rolling-tribes',
    name: 'Rolling Tribes',
    roleDescription: {
      EN: 'The architectural minds behind the night. Rolling Tribes is a collective of velocity addicts and urban navigators dedicated to reclaiming the concrete sprawl. They engineer the routes, establish the protocols, and ensure the grid remains electrified for every rider entering the zone.',
      FR: "Les architectes au cœur de l'événement. Rolling Tribes est un collectif de passionnés de vitesse et de navigateurs urbains dévoués à s'approprier les espaces urbains. Ils conçoivent les parcours, établissent les protocoles de sécurité et veillent à dynamiser chaque kilomètre pour tous les patineurs.",
      ES: 'Las mentes maestras detrás del evento. Rolling Tribes es un colectivo de apasionados por la velocidad y exploradores urbanos dedicados a conquistar el asfalto. Diseñan las rutas, establecen los protocolos de seguridad y aseguran que la energía se mantenga al máximo para cada participante.',
    },
    entityId: 'RLL_TRB_01',
    image: '/organizers/rolling_tribes_logo.jpg',
    tags: ['ROUTING', 'LOGISTICS', 'OVERSEER'],
    website: 'https://rollingtribes.com',
    instagramUrl: 'https://www.instagram.com/rollingtribes/',
  },
  {
    id: 'org-city-verdun',
    name: 'Arrondissement de Verdun',
    roleDescription: {
      EN: 'Official municipal host and territorial partner for MONTRÉAL ROLL 2026. Arrondissement de Verdun powers the grid by opening prime waterfront plazas, pump track hubs, and protected urban corridors, championing active mobility and community skate culture.',
      FR: "Arrondissement hôte officiel et partenaire territorial de MONTRÉAL ROLL 2026. L'arrondissement de Verdun soutient le festival en ouvrant ses magnifiques berges, ses installations de pumptrack et ses corridors urbains protégés, valorisant la mobilité active et la culture du patinage.",
      ES: 'Anfitrión municipal oficial y aliado territorial de MONTRÉAL ROLL 2026. La alcaldía de Verdun impulsa el evento abriendo sus plazas costeras, circuitos de pumptrack y corredores urbanos protegidos, promoviendo la movilidad activa y la cultura del patinaje.',
    },
    entityId: 'ARR_VRDN_02',
    image: '/organizers/verdun_logo.svg',
    tags: ['HOST_BOROUGH', 'CIVIC_PARTNER', 'URBAN_CORRIDORS', 'ACTIVE_MOBILITY'],
    website: 'https://montreal.ca/verdun',
    instagramUrl: 'https://www.instagram.com/arr_verdun',
  }
];

export const SPONSORS: Sponsor[] = [
  {
    id: 'spon-rockin',
    name: 'ROCKIN\' FRAMES',
    image: '/sponsors/rockin.png',
    website: 'https://rockinframes.com',
  },
  {
    id: 'spon-solo',
    name: 'Boutique Solo-Inline',
    image: '/sponsors/solo.png',
    website: 'https://solo-inline.com/'
  },
  {
    id: 'spon-lowlife',
    name: 'Lowlife Mtl',
    image: '/sponsors/lowlife.png',
    website: 'https://www.lowlifemtl.com/'
  },
  {
    id: 'spon-skpro',
    name: 'SkatePro',
    image: '/sponsors/skatepro.png',
    website: 'https://www.skatepro.ca/'
  },
  {
    id: 'spon-prosk8place',
    name: 'ProSkaters Place',
    image: '/sponsors/proskaterplace.png',
    website: 'https://proskatersplace.ca/'
  },
  {
    id: 'spon-flyingeagle',
    name: 'FlyingEagle Skate',
    image: '/sponsors/flyingeagle.png',
    website: 'https://www.flyingeagleskates.com/'
  },
  {
    id: 'spon-yoyo',
    name: 'YOYOSKATE',
    image: '/sponsors/yoyo.png',
    website: 'https://www.yoyoskateofficial.com/'
  }
];

export const TIMETABLE_EVENTS: TimetableEvent[] = [
  // Day 1 - Friday, Sept 11
  {
    id: 'time-d1-1',
    title: {
      EN: 'Urban Street Ride 20km',
      FR: 'Randonnée urbaine 20kms',
      ES: 'Ruta Urbana de 20 km',
    },
    description: {
      EN: 'Easy scenic ride along the waterfront, passing by the LaSalle skatepark and pumptrack; by Rolling Tribes.',
      FR: 'Randonnée tranquille le long de l’eau, en passant par le skatepark et pumptrack de LaSalle ; par Rolling Tribes.',
      ES: 'Paseo tranquilo junto al agua, pasando por el skatepark y pumptrack de LaSalle; por Rolling Tribes.',
    },
    longDescription: {
      EN: 'A scenic and relaxed 20km group roll along the waterfront of Montreal, routing through LaSalle skatepark and the local pumptrack. Led and escorted by the Rolling Tribes crew.',
      FR: 'Randonnée tranquille de 20 km le long de l’eau, en passant par le skatepark et pumptrack de LaSalle ; organisée et encadrée par Rolling Tribes.',
      ES: 'Recorrido panorámico y tranquilo de 20 km junto a la orilla del agua, pasando por el skatepark y pumptrack de LaSalle; organizado y guiado por Rolling Tribes.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '10:00 - 12:00',
    level: 'intermediate',
    startLocation: {
      EN: 'Parc du Souvenir (Verdun Metro)',
      FR: 'Parc du Souvenir (Métro Verdun)',
      ES: 'Parc du Souvenir (Metro Verdun)',
    },
    endLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    category: {
      EN: 'Street Ride',
      FR: 'Randonnée Urbaine',
      ES: 'Ruta Urbana',
    },
    type: 'ride',
    day: 1,
    iconName: 'directions_bike',
  },
  {
    id: 'time-d1-2',
    title: {
      EN: 'Open Skate & Warm-Up',
      FR: 'Patinage libre',
      ES: 'Patinaje Libre y Calentamiento',
    },
    description: {
      EN: 'Setup, open skating, and warm-up session.',
      FR: 'Mise en place et échauffement.',
      ES: 'Puesta en marcha y calentamiento.',
    },
    longDescription: {
      EN: 'Free open skating session at the rink to warm up, dial in your frames, test gear, and meet the community before the workshops begin.',
      FR: 'Session de patinage libre pour s\'échauffer, tester son matériel, ajuster ses platines et se retrouver avant le début des ateliers.',
      ES: 'Sesión de patinaje libre en la pista para calentar, ajustar patines y compartir con la comunidad antes del inicio de los talleres.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzIYd8nyAicsDj0p9QMw0vc_OypY39Qi03q0N_nV2O9EkC9DmBiDS8VszGJGjdHD-Q7d01ywp0A6xGw1wqhRZnXfdWLJ7oDHSdPCDdacR6jox0ay6ByqcF0vqzVhG1U8N5QEOvUDL_kM1tdY-B4oTeUMUJk9bp_aUq1t407HctiUyKcpMOuhxJJcu9j-sFO1rDOgw3Ts73e8m-CiwhsK9C9-xMAS0iDUgpnTPFewCZ6D1H0a-IVUfa',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '13:00 - 14:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Open Skate',
      FR: 'Patinage libre',
      ES: 'Patinaje libre',
    },
    type: 'social',
    day: 1,
    iconName: 'sparkles',
  },
  {
    id: 'time-d1-3',
    title: {
      EN: 'Skate Technique Masterclass with VRL',
      FR: 'Techniques de patin avec VRL',
      ES: 'Técnicas de Patinaje con VRL',
    },
    description: {
      EN: 'Mathieu Way and Pierra Vernex from VRL Speed Skating Club share a championship speed training session. Bring shoes and helmet.',
      FR: 'Mathieu Way et Pierra Vernex du club de patin VRL partagent une séance de leur entrainement de champion de patinage de vitesse. Apportez chaussures et casque.',
      ES: 'Mathieu Way y Pierra Vernex del club de patinaje VRL comparten una sesión de su entrenamiento de campeones de patinaje de velocidad. Trae calzado deportivo y casco.',
    },
    longDescription: {
      EN: 'Learn elite speed skating dynamics, stride mechanics, pushing efficiency, and edge control from champions Mathieu Way and Pierra Vernex of the VRL club. Please bring sneakers/running shoes for dryland prep and a helmet.',
      FR: 'Mathieu Way et Pierra Vernex du club de patin VRL partagent une séance de leur entrainement de champion de patinage de vitesse : technique de poussée, virages et contrôle des carres. Apportez chaussures de sport et casque.',
      ES: 'Aprende biomecánica de empuje, técnica de zancada y control de cantos con los campeones Mathieu Way y Pierra Vernex del club VRL. Por favor trae zapatillas deportivas para calentamiento en seco y casco.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '14:00 - 16:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 1,
    iconName: 'school',
  },
  {
    id: 'time-d1-4',
    title: {
      EN: 'Ça SLALOM! Freestyle Workshop',
      FR: 'Ça SLALOM !',
      ES: '¡Ça SLALOM! Taller de Freestyle',
    },
    description: {
      EN: 'Instruction in basic and advanced slalom tricks and cone flows, coached by Karen and Kaia from Rolling Tribes.',
      FR: 'Enseignement de figures de slalom basiques et avancées, encadré par Karen et Kaia de Rolling Tribes.',
      ES: 'Enseñanza de trucos de slalom básicos y avanzados, guiado por Karen y Kaia de Rolling Tribes.',
    },
    longDescription: {
      EN: 'From your first fish and snake cone runs to advanced footwork and spins, Karen and Kaia from Rolling Tribes break down freestyle cone technique step-by-step.',
      FR: 'Des premières passes aux figures avancées et combos autour des cônes, Karen et Kaia de Rolling Tribes décomposent les mouvements de slalom étape par étape.',
      ES: 'Desde las primeras líneas de conos hasta combinaciones y giros avanzados, Karen y Kaia de Rolling Tribes te enseñan técnicas de freestyle slalom paso a paso.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzIYd8nyAicsDj0p9QMw0vc_OypY39Qi03q0N_nV2O9EkC9DmBiDS8VszGJGjdHD-Q7d01ywp0A6xGw1wqhRZnXfdWLJ7oDHSdPCDdacR6jox0ay6ByqcF0vqzVhG1U8N5QEOvUDL_kM1tdY-B4oTeUMUJk9bp_aUq1t407HctiUyKcpMOuhxJJcu9j-sFO1rDOgw3Ts73e8m-CiwhsK9C9-xMAS0iDUgpnTPFewCZ6D1H0a-IVUfa',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '16:00 - 17:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 1,
    iconName: 'brush',
  },
  {
    id: 'time-d1-5',
    title: {
      EN: 'WIZARD Skating Workshop',
      FR: 'Atelier de patinage WIZARD',
      ES: 'Taller de Patinaje WIZARD',
    },
    description: {
      EN: 'Instruction in Wizard style movement, rocker edge flow, and combos, coached by Seb from Rolling Tribes.',
      FR: 'Enseignement de mouvements et combos du style Wizard, encadré par Seb de Rolling Tribes.',
      ES: 'Enseñanza de movimientos y combinaciones del estilo Wizard, guiado por Seb de Rolling Tribes.',
    },
    longDescription: {
      EN: 'Discover the flow, Gazelle transitions, and rockered frame carving dynamics of Wizard skating. Seb from Rolling Tribes guides beginners through foundational weight distribution and fluid body turns.',
      FR: 'Découvrez la fluidité, les transitions Gazelle et les appuis sur platines rockered propres au patinage Wizard. Seb de Rolling Tribes guide les débutants sur les transferts de poids et les rotations du corps.',
      ES: 'Descubre la fluidez, transiciones Gazelle y tallado con guías rockered del patinaje estilo Wizard. Seb de Rolling Tribes guía a principiantes en distribución de peso y giros fluidos.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '17:00 - 18:00',
    level: 'beginner',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 1,
    iconName: 'school',
  },
  {
    id: 'time-d1-6',
    title: {
      EN: 'Skate Games & Fun Challenges',
      FR: 'Jeux',
      ES: 'Juegos y Desafíos en Patines',
    },
    description: {
      EN: 'Various fun skating games, agility challenges, and friendly community activities.',
      FR: 'Différents jeux et défis ludiques sur patins.',
      ES: 'Diferentes juegos divertidos y retos de agilidad sobre ruedas.',
    },
    longDescription: {
      EN: 'Fun community games and agility challenges on wheels for all participants. Great laughs, prize giveaways, and friendly energy.',
      FR: 'Jeux collectifs amusants et défis d\'agilité sur roulettes pour tous les participants. Bonne humeur et ambiance festive garanties.',
      ES: 'Juegos comunitarios divertidos y desafíos de agilidad sobre patines para todos los participantes. Risas, premios y excelente ambiente.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzIYd8nyAicsDj0p9QMw0vc_OypY39Qi03q0N_nV2O9EkC9DmBiDS8VszGJGjdHD-Q7d01ywp0A6xGw1wqhRZnXfdWLJ7oDHSdPCDdacR6jox0ay6ByqcF0vqzVhG1U8N5QEOvUDL_kM1tdY-B4oTeUMUJk9bp_aUq1t407HctiUyKcpMOuhxJJcu9j-sFO1rDOgw3Ts73e8m-CiwhsK9C9-xMAS0iDUgpnTPFewCZ6D1H0a-IVUfa',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '18:00 - 19:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Games',
      FR: 'Jeux',
      ES: 'Juegos',
    },
    type: 'social',
    day: 1,
    iconName: 'trophy',
  },
  {
    id: 'time-d1-7',
    title: {
      EN: 'Tranquille à Roulettes (Roller Disco)',
      FR: 'Tranquille à roulettes',
      ES: 'Tranquille à Roulettes (Roller Disco)',
    },
    description: {
      EN: 'Groove to Patins Platines (DJ Arielle Roberge) with dance moves by Marly. Free admission, with skate & gear rental on-site if needed.',
      FR: 'Vibre au rythme de Patins Platines (DJ Arielle Roberge) avec les moves de Marly. Accès gratuit et location de patins et protections sur place si besoin.',
      ES: 'Disfruta al ritmo de Patins Platines (DJ Arielle Roberge) con los pasos de baile de Marly. Acceso gratuito y alquiler de patines y protecciones en el lugar si se requiere.',
    },
    longDescription: {
      EN: 'The signature Montreal roller disco night on the heart of Esplanade Tranquille. Dance and skate under city lights with DJ Arielle Roberge (Patins Platines) and dance leader Marly. Free entrance for all, with on-site skate and protective gear rental available.',
      FR: 'La soirée roller disco incontournable au cœur de l\'Esplanade Tranquille. Dansez et patinez sous les lumières urbaines au son de Patins Platines (DJ Arielle Roberge) et des chorégraphies de Marly. Entrée gratuite, location de patins et équipements disponible sur place.',
      ES: 'La noche imperdible de roller disco en el corazón de la Esplanade Tranquille. Baila y patina bajo las luces de la ciudad con DJ Arielle Roberge (Patins Platines) y las coreografías de Marly. Entrada gratuita con alquiler de patines y protecciones disponible.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBk23iiPsQondimS8L4yxRofJ4bhsP047QTlBPD9Q2yAq81d3NVWmJPkMoTr-538WC-BYjgSUwL2KujXsd86RSSIWoIUPFWDCjC5znhkqE4sNF6ERE4RBrz1NAHjpvdYcCzVPhl3-Zxr86kRXEL4pew3b0hF0wcEmcXlS-W5jMlp00OGwHKc4tUvXNDcF2u6iZERWETMLoSwYmpfSpLYCqlrL4J03o2ZyXAxyJT3Z-l3270gFsqfT5g',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '19:00 - 23:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Esplanade Tranquille (Quartier des Spectacles)',
      FR: 'Esplanade Tranquille (Quartier des spectacles)',
      ES: 'Esplanade Tranquille (Quartier des spectacles)',
    },
    endLocation: undefined,
    category: {
      EN: 'Roller Disco',
      FR: 'Roller disco',
      ES: 'Roller disco',
    },
    type: 'social',
    day: 1,
    iconName: 'sparkles',
  },
  {
    id: 'time-d1-8',
    title: {
      EN: 'Light Up the 514: MTL ROLL Special (Outbound)',
      FR: 'Illumine le 514 : Spécial MTL ROLL (Aller)',
      ES: 'Ilumina el 514: Especial MTL ROLL (Ida)',
    },
    description: {
      EN: 'Join Rolling Tribes\' famous illuminated night ride with lights & music through downtown & the Old Port, arriving at Esplanade Tranquille for the final roller disco hour.',
      FR: 'Participe à la fameuse randonnée nocturne de Rolling Tribes toute en lumière et en musique, et visite le centre ville ainsi que le vieux port, pour arriver à l\'esplanade tranquille et profiter de la derniere heure de roller disco.',
      ES: 'Participa en la famosa ruta nocturna de Rolling Tribes con luces y música por el centro y el Puerto Viejo, llegando a la Esplanade Tranquille para la última hora de roller disco.',
    },
    longDescription: {
      EN: 'Join Rolling Tribes for the celebrated "Illumine le 514" night cruise. Bedecked in glowing neon LED arrays and rolling sound systems, we carve through Verdun, downtown Montreal, and the historic Old Port, rolling right onto Esplanade Tranquille to catch the climactic finale of the roller disco.',
      FR: 'Rejoignez la célèbre randonnée nocturne "Illumine le 514" de Rolling Tribes. Équipés de lumières et d\'enceintes mobiles, nous sillonnons Verdun, le centre-ville et le Vieux-Port pour débarquer sur l\'Esplanade Tranquille et savourer la dernière heure de roller disco.',
      ES: 'Únete a la emblemática ruta nocturna "Illumine le 514" de Rolling Tribes. Equipados con luces y música móvil, recorremos Verdun, el centro y el Puerto Viejo hasta llegar a la Esplanade Tranquille para disfrutar del gran final del roller disco.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '20:30 - 22:00',
    level: 'intermediate',
    startLocation: {
      EN: 'Parc du Souvenir (Verdun Metro)',
      FR: 'Parc du Souvenir (Métro Verdun)',
      ES: 'Parc du Souvenir (Metro Verdun)',
    },
    endLocation: {
      EN: 'Esplanade Tranquille (Quartier des Spectacles)',
      FR: 'Esplanade Tranquille (Quartier des spectacles)',
      ES: 'Esplanade Tranquille (Quartier des spectacles)',
    },
    category: {
      EN: 'Street Ride',
      FR: 'Randonnée Urbaine',
      ES: 'Ruta Urbana',
    },
    type: 'ride',
    day: 1,
    iconName: 'directions_bike',
  },
  {
    id: 'time-d1-9',
    title: {
      EN: 'Light Up the 514: MTL ROLL Special (Return)',
      FR: 'Illumine le 514 : Spécial MTL ROLL (Retour)',
      ES: 'Ilumina el 514: Especial MTL ROLL (Regreso)',
    },
    description: {
      EN: 'An easy-paced night return cruise on skates back to Verdun Metro for anyone wanting to roll home together.',
      FR: 'On rentre tranquillement jusqu\'au métro Verdun en patin, pour celles et ceux qui en ont envie.',
      ES: 'Regreso tranquilo sobre patines hasta la estación de metro Verdun para quienes deseen volver en grupo.',
    },
    longDescription: {
      EN: 'A friendly, relaxed group night ride rolling back from Esplanade Tranquille through quiet midnight streets to Verdun Metro. The perfect end to Day 1.',
      FR: 'Randonnée de retour nocturne conviviale et détendue depuis l\'Esplanade Tranquille à travers les rues calmes jusqu\'au métro Verdun. La conclusion idéale du Jour 1.',
      ES: 'Recorrido nocturno grupal tranquilo y amigable desde la Esplanade Tranquille por calles nocturnas hasta el metro Verdun. El cierre perfecto para el Día 1.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBk23iiPsQondimS8L4yxRofJ4bhsP047QTlBPD9Q2yAq81d3NVWmJPkMoTr-538WC-BYjgSUwL2KujXsd86RSSIWoIUPFWDCjC5znhkqE4sNF6ERE4RBrz1NAHjpvdYcCzVPhl3-Zxr86kRXEL4pew3b0hF0wcEmcXlS-W5jMlp00OGwHKc4tUvXNDcF2u6iZERWETMLoSwYmpfSpLYCqlrL4J03o2ZyXAxyJT3Z-l3270gFsqfT5g',
    date: {
      EN: 'Friday, Sept 11, 2026',
      FR: 'Vendredi 11 sept. 2026',
      ES: 'Viernes 11 sept. 2026',
    },
    time: '23:15 - 23:59',
    level: 'intermediate',
    startLocation: {
      EN: 'Esplanade Tranquille (Quartier des Spectacles)',
      FR: 'Esplanade Tranquille (Quartier des spectacles)',
      ES: 'Esplanade Tranquille (Quartier des spectacles)',
    },
    endLocation: {
      EN: 'Parc du Souvenir (Verdun Metro)',
      FR: 'Parc du Souvenir (Métro Verdun)',
      ES: 'Parc du Souvenir (Metro Verdun)',
    },
    category: {
      EN: 'Street Ride',
      FR: 'Randonnée Urbaine',
      ES: 'Ruta Urbana',
    },
    type: 'ride',
    day: 1,
    iconName: 'directions_bike',
  },

  // Day 2 - Saturday, Sept 12
  {
    id: 'time-d2-1',
    title: {
      EN: 'Skatepark Workshop',
      FR: 'Atelier Skatepark',
      ES: 'Taller de Skatepark',
    },
    description: {
      EN: 'Xavier from Rolling Tribes teaches basic and advanced skatepark techniques tailored to your skill level. Helmet and pads required.',
      FR: 'Xavier de Rolling Tribes vous montrera les techniques de bases et avancées pour s\'amuser en Skatepark selon votre niveau. Apportez casque et protections.',
      ES: 'Xavier de Rolling Tribes te enseñará técnicas básicas y avanzadas para divertirte en el Skatepark según tu nivel. Trae casco y protecciones.',
    },
    longDescription: {
      EN: 'Learn park transitions, dropping in, pumping bowls, coping stalls, and jump safety with Xavier from Rolling Tribes. Structured for beginner to intermediate park skaters. Protective gear (helmet, knee, elbow, wrist guards) mandatory.',
      FR: 'Apprenez les transitions en courbe, les drops, le pompage dans les bowls et la sécurité en skatepark avec Xavier de Rolling Tribes. Adapté selon votre niveau. Casque et protections complets obligatoires.',
      ES: 'Aprende transiciones en rampa, drops, bombeo en bowl y seguridad en el skatepark con Xavier de Rolling Tribes. Adaptado a tu nivel. Casco y protecciones completas obligatorios.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD-_Ict4THRYVHUB8CLRsQjgip0_D30ZyoyF3yuGBHdka_2AoHhMmS9U6mAhb27nWMMs3BBRNqfKVwy6kfq8sz8PmtLkrxyWtaPp4TSQBSk7UMiNpERlxI8-680gry-LjbhUsgZUsqRaHxzTfrRQ6-yh7DOA76n1FMmzJeTY_J-CRZF08Ei8v6bewiMx3ZrF2rSd7FLtZ9MoNHkbLYjc_bqWQis-tSHZlQWJyvXG7ejVkQfcMDwSu2J',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '10:00 - 11:30',
    level: 'beginner',
    startLocation: {
      EN: 'Arthur Therrien Park Skatepark',
      FR: 'Planchodrome du parc Arthur Therrien',
      ES: 'Planchódromo del parque Arthur Therrien',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 2,
    iconName: 'school',
  },
  {
    id: 'time-d2-2',
    title: {
      EN: 'Pumptrack Workshop',
      FR: 'Atelier Pumptrack',
      ES: 'Taller de Pumptrack',
    },
    description: {
      EN: 'Dave and Melina, extreme downhill & ice cross specialists, teach techniques and tips to conquer a pumptrack with maximum efficiency. Helmet and pads required.',
      FR: 'Dave et Melina sont spécialisés en patinage de descente extreme (ice cross) et vous enseignerons techniques et conseils pour franchir une piste à bosse le plus efficacement possible. Apportez casque et protections.',
      ES: 'Dave y Melina, especialistas en descenso extremo (ice cross), te enseñarán técnicas y consejos para superar una pista de bumps con la máxima eficacia. Trae casco y protecciones.',
    },
    longDescription: {
      EN: 'Master the physics of weight transfer, pumping rollers, berm carving, and acceleration without pushing. Coached by downhill ice cross athletes Dave & Melina. Full protective gear and helmet mandatory.',
      FR: 'Maîtrisez les transferts de poids, le pompage des bosses, la prise de virages relevés et la prise de vitesse sans patiner. Encadré par Dave et Melina, experts en ice cross. Casque et protections obligatoires.',
      ES: 'Domina los traslados de peso, bombeo en desniveles y curvas peraltadas para ganar velocidad sin impulsarte. Impartido por Dave y Melina, atletas de ice cross. Casco y protecciones obligatorios.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '11:30 - 13:00',
    level: 'beginner',
    startLocation: {
      EN: 'D\'Argenson Park Pumptrack',
      FR: 'Pumptrack du parc d\'Argenson',
      ES: 'Pumptrack del parque d\'Argenson',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 2,
    iconName: 'directions_bike',
  },
  {
    id: 'time-d2-3',
    title: {
      EN: 'Urban Street Art Ride 5km',
      FR: 'Randonnée urbaine 5kms',
      ES: 'Ruta Urbana de Arte Callejero 5 km',
    },
    description: {
      EN: 'A gentle skate stroll through the streets of Verdun to discover and appreciate local Street Art.',
      FR: 'Une légère promenade en patin dans les rues de Verdun pour apprécier le Street Art local.',
      ES: 'Un paseo suave en patines por las calles de Verdun para apreciar el Street Art local.',
    },
    longDescription: {
      EN: 'An accessible, relaxing 5km group ride rolling through Verdun’s scenic streets and artistic alleyways with photo stops at prominent murals and street art installations.',
      FR: 'Randonnée accessible et conviviale de 5 km à travers les rues de Verdun et ses ruelles artistiques, avec arrêts photos devant les plus belles murales locales.',
      ES: 'Recorrido accesible y relajado de 5 km por las calles de Verdun y sus callejones artísticos, con paradas para admirar y fotografiar los murales locales.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBo4OsmywxyzTBGMpyJ2bONw_D0vlGKtLZIUtQ4wCtoFmboYAd8JRtC56FQUMeY8x9V8dzM_NfKPZx3nWcaZ-Sl4MOCRIbSLJQWf2iyqQohqSR3A_ehGXIy2s8JKHmB3JdIyFoQFP6DRGkHWg8OZCF8NMnXp-wK4XDzjSuww4NIBVKO79hSU39GeE8hzJPDSmXzxEfLubeML19YdskJ-qsNR1-1XIFxYW_ZjYVFVuti1sqlSA6uLIU0',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '14:00 - 15:00',
    level: 'beginner',
    startLocation: {
      EN: 'Verdun Metro Station',
      FR: 'Métro Verdun',
      ES: 'Metro Verdun',
    },
    endLocation: {
      EN: 'Verdun Metro Station',
      FR: 'Métro Verdun',
      ES: 'Metro Verdun',
    },
    category: {
      EN: 'Street Ride',
      FR: 'Randonnée Urbaine',
      ES: 'Ruta Urbana',
    },
    type: 'ride',
    day: 2,
    iconName: 'brush',
  },
  {
    id: 'time-d2-4',
    title: {
      EN: 'Ça SLALOM! Freestyle Workshop',
      FR: 'Ça SLALOM !',
      ES: '¡Ça SLALOM! Taller de Freestyle',
    },
    description: {
      EN: 'Instruction in basic and advanced slalom figures and footwork, coached by Karen and Kaia from Rolling Tribes.',
      FR: 'Enseignement de figures de slalom basiques et avancées, encadré par Karen et Kaia de Rolling Tribes.',
      ES: 'Enseñanza de figuras de slalom básicas y avanzadas, guiado por Karen y Kaia de Rolling Tribes.',
    },
    longDescription: {
      EN: 'Perfect your cone carving, crossovers, and rhythmic footwork with Karen & Kaia from Rolling Tribes on the smooth concrete of Willibrord rink.',
      FR: 'Perfectionnez vos figures autour des cônes, croisements et jeux de jambes avec Karen et Kaia de Rolling Tribes sur la surface lisse du parc Willibrord.',
      ES: 'Perfecciona tus figuras de conos, cruces y juego de pies con Karen y Kaia de Rolling Tribes en la pista del parque Willibrord.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzIYd8nyAicsDj0p9QMw0vc_OypY39Qi03q0N_nV2O9EkC9DmBiDS8VszGJGjdHD-Q7d01ywp0A6xGw1wqhRZnXfdWLJ7oDHSdPCDdacR6jox0ay6ByqcF0vqzVhG1U8N5QEOvUDL_kM1tdY-B4oTeUMUJk9bp_aUq1t407HctiUyKcpMOuhxJJcu9j-sFO1rDOgw3Ts73e8m-CiwhsK9C9-xMAS0iDUgpnTPFewCZ6D1H0a-IVUfa',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '15:30 - 16:30',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 2,
    iconName: 'timeline',
  },
  {
    id: 'time-d2-5',
    title: {
      EN: 'SKATESPACE Foundations & Intro',
      FR: 'Initiations par SKATESPACE',
      ES: 'Iniciación al Patinaje por SKATESPACE',
    },
    description: {
      EN: 'Learn the core fundamentals of skating or brush up on your essential stance, balance, and stopping.',
      FR: 'Pour apprendre les bases du patinage ou les réviser.',
      ES: 'Para aprender las bases del patinaje o repasarlas.',
    },
    longDescription: {
      EN: 'Ideal for beginners and those looking to build rock-solid confidence. The SKATESPACE instructors break down balance, stride, turning, and reliable stopping techniques in a welcoming environment.',
      FR: 'Idéal pour les débutants et ceux qui souhaitent consolider leurs bases : posture, équilibre, propulsion, virages et freinages en toute sécurité avec l\'équipe SKATESPACE.',
      ES: 'Ideal para principiantes y quienes buscan consolidar su confianza: postura, equilibrio, deslizamiento, giros y frenadas seguras con los instructores de SKATESPACE.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGtm6jK2gS9pavNm6jz5SH78XNkpBRlByAo36kawzTStCMCJWYmZDHSmFxJA65lvTw8t7zt04GLIQyw1RzK2wuO05f9ZUaAlWtvbO0aBn3eJYWya9H6nsp3DxS7hNByQEjXU3KTQwIMIXkc0poEBPheC_ZLEE9T_YNzd8qje1-WGGFqKJmuIpyaCUb_hfOnjQh6gB6tvT__tk1NoJ2zBkZsKku1Z9MZ1hdAsg0SCfd8F8nraYwsNCR',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '15:30 - 16:30',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 2,
    iconName: 'school',
  },
  {
    id: 'time-d2-6',
    title: {
      EN: 'Slide & Powerslide Workshop',
      FR: 'Atelier de dérapage',
      ES: 'Taller de Derrapes y Slides',
    },
    description: {
      EN: 'What is more fun than sliding on asphalt like on ice? Coached by Saul & Seb from Rolling Tribes.',
      FR: 'Quoi de plus amusant que de glisser sur l\'asphalte comme sur de la glace ? Encadré par Saul & Seb de Rolling Tribes.',
      ES: '¿Qué hay más divertido que deslizarse sobre el asfalto como sobre hielo? Guiado por Saul y Seb de Rolling Tribes.',
    },
    longDescription: {
      EN: 'Learn the biomechanics of wheel slides: powerslide, soul slide, parallel slide, and acid slide. Master wheel angle control and bodyweight distribution with Saul and Seb from Rolling Tribes.',
      FR: 'Apprenez la biomécanique des slides sur roulettes : powerslide, soul slide, parallel slide et acid slide. Contrôlez vos angles de roues et vos appuis avec Saul et Seb de Rolling Tribes.',
      ES: 'Aprende la técnica de derrapes sobre ruedas: powerslide, soul slide, parallel slide y acid slide. Controla la inclinación de tus ruedas y peso corporal con Saul y Seb de Rolling Tribes.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '16:30 - 17:30',
    level: 'beginner',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 2,
    iconName: 'sparkles',
  },
  {
    id: 'time-d2-7',
    title: {
      EN: 'Roller Dance with SKATESPACE',
      FR: 'Roller Dance par SKATESPACE',
      ES: 'Roller Dance por SKATESPACE',
    },
    description: {
      EN: 'Skates and dance, what could be more stylish?',
      FR: 'Patins et danse, quoi de plus stylé ?',
      ES: 'Patines y baile, ¿qué puede tener más estilo?',
    },
    longDescription: {
      EN: 'Learn rhythmic steps, downtown grooves, spins, and choreography on quad or inline skates guided by the SKATESPACE dance crew.',
      FR: 'Apprenez des pas de danse rythmés, des enchaînements groove, des tours et des chorégraphies sur patins à roulettes et rollers avec SKATESPACE.',
      ES: 'Aprende pasos rítmicos, giros y coreografías sobre patines guiado por el equipo de danza de SKATESPACE.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzIYd8nyAicsDj0p9QMw0vc_OypY39Qi03q0N_nV2O9EkC9DmBiDS8VszGJGjdHD-Q7d01ywp0A6xGw1wqhRZnXfdWLJ7oDHSdPCDdacR6jox0ay6ByqcF0vqzVhG1U8N5QEOvUDL_kM1tdY-B4oTeUMUJk9bp_aUq1t407HctiUyKcpMOuhxJJcu9j-sFO1rDOgw3Ts73e8m-CiwhsK9C9-xMAS0iDUgpnTPFewCZ6D1H0a-IVUfa',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '16:30 - 17:30',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 2,
    iconName: 'music',
  },
  {
    id: 'time-d2-8',
    title: {
      EN: 'Open Skate & Chill Session',
      FR: 'Patinage libre',
      ES: 'Patinaje Libre y Convivencia',
    },
    description: {
      EN: 'We chill on wheels.',
      FR: 'On chill en patin.',
      ES: 'A rodar y relajarse en patines.',
    },
    longDescription: {
      EN: 'Open floor skate time to roll with friends, practice your moves, listen to music, and relax at the rink.',
      FR: 'Session de patinage libre pour rouler entre amis, pratiquer ses figures, écouter de la bonne musique et profiter de la piste.',
      ES: 'Tiempo de patinaje libre para rodar con amigos, practicar trucos, escuchar música y relajarse en la pista.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBk23iiPsQondimS8L4yxRofJ4bhsP047QTlBPD9Q2yAq81d3NVWmJPkMoTr-538WC-BYjgSUwL2KujXsd86RSSIWoIUPFWDCjC5znhkqE4sNF6ERE4RBrz1NAHjpvdYcCzVPhl3-Zxr86kRXEL4pew3b0hF0wcEmcXlS-W5jMlp00OGwHKc4tUvXNDcF2u6iZERWETMLoSwYmpfSpLYCqlrL4J03o2ZyXAxyJT3Z-l3270gFsqfT5g',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '17:30 - 18:30',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Open Skate',
      FR: 'Patinage libre',
      ES: 'Patinaje libre',
    },
    type: 'social',
    day: 2,
    iconName: 'sparkles',
  },
  {
    id: 'time-d2-9',
    title: {
      EN: 'FREESTYLE with Émile',
      FR: 'FREESTYLE avec Émile',
      ES: 'FREESTYLE con Émile',
    },
    description: {
      EN: 'Stylish tricks and flows to the rhythm of upbeat music.',
      FR: 'Des figures stylées au rythme de la musique enjouée.',
      ES: 'Trucos con estilo al ritmo de música animada.',
    },
    longDescription: {
      EN: 'Join Émile for an energetic freestyle workshop exploring musicality, artistic transitions, jumps, and creative combinations on wheels.',
      FR: 'Rejoignez Émile pour un atelier freestyle plein d\'énergie alliant musicalité, transitions artistiques, petits sauts et enchaînements créatifs.',
      ES: 'Únete a Émile en un taller de freestyle enérgico que combina musicalidad, transiciones artísticas, saltos y combinaciones creativas.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDaEtvIx3NC3aokEq5kAnJDSJej_iPs2Ir0RXyjztW_Bo-vgBwr2NREvtKYDGAKjGBvJ-mKODUcLe7js9QKoJto-O-z9W2doNrsIiazWALsCJWxQpYugsn_vInMSp6elnmQ0aDv--AnPNJHalMz7dl_99mSwqqei5OC0BM19vf8yu7Uug4CKtI6cVFwxLuoWYiC3nxV2MoyMjFDnxj5lVJASm0zmIASXFPtHWW5ZfU5G0EkvuHVBDiN',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '17:30 - 18:30',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 2,
    iconName: 'auto_awesome',
  },
  {
    id: 'time-d2-10',
    title: {
      EN: 'Dance Contest',
      FR: 'Dance contest',
      ES: 'Concurso de Baile sobre Ruedas',
    },
    description: {
      EN: 'Sign up, choose your track, and showcase your unique choreographic style!',
      FR: 'Inscris-toi, choisis ta musique, et expose ton style chorégraphique unique !',
      ES: '¡Inscríbete, elige tu música y muestra tu estilo coreográfico único!',
    },
    longDescription: {
      EN: 'The official MTL ROLL Dance Contest! Bring your track, show off your signature moves, and battle in front of enthusiastic judges and an energized crowd. Prizes for top style and crowd favorite.',
      FR: 'Le grand concours de danse MTL ROLL ! Choisissez votre musique, dévoilez vos chorégraphies et affrontez d\'autres patineurs devant un jury et un public en feu. Prix pour les meilleures performances.',
      ES: '¡El gran concurso de baile de MTL ROLL! Elige tu pista musical, demuestra tus mejores pasos y compite ante los jueces y el público. Premios para los estilos más destacados.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD-_Ict4THRYVHUB8CLRsQjgip0_D30ZyoyF3yuGBHdka_2AoHhMmS9U6mAhb27nWMMs3BBRNqfKVwy6kfq8sz8PmtLkrxyWtaPp4TSQBSk7UMiNpERlxI8-680gry-LjbhUsgZUsqRaHxzTfrRQ6-yh7DOA76n1FMmzJeTY_J-CRZF08Ei8v6bewiMx3ZrF2rSd7FLtZ9MoNHkbLYjc_bqWQis-tSHZlQWJyvXG7ejVkQfcMDwSu2J',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '18:30 - 19:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Competition',
      FR: 'Atelier',
      ES: 'Competición',
    },
    type: 'competition',
    day: 2,
    iconName: 'trophy',
  },
  {
    id: 'time-d2-11',
    title: {
      EN: 'Saturday Night Fever... On Skates!',
      FR: 'La fièvre du Samedi Soir... En patin !',
      ES: '¡Fiebre de Sábado por la Noche... en Patines!',
    },
    description: {
      EN: 'The dance floor is yours, roll in music under the coolness of the night!',
      FR: 'La piste de danse est à toi, roule en musique sous la fraîcheur de la nuit !',
      ES: '¡La pista de baile es tuya, rueda con música bajo la frescura de la noche!',
    },
    longDescription: {
      EN: 'The Saturday night roller dance party! Electric lights, infectious beats, and open dance floor on skates at the Willibrord rink until 10 PM.',
      FR: 'La grande soirée roller dance du samedi soir ! Musique entraînante, lumières festives et piste ouverte à tous pour patiner et danser sous les étoiles jusqu\'à 22h.',
      ES: '¡La gran fiesta de roller dance del sábado por la noche! Música contagiosa, luces festivas y pista abierta para patinar y bailar bajo las estrellas hasta las 22:00.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzIYd8nyAicsDj0p9QMw0vc_OypY39Qi03q0N_nV2O9EkC9DmBiDS8VszGJGjdHD-Q7d01ywp0A6xGw1wqhRZnXfdWLJ7oDHSdPCDdacR6jox0ay6ByqcF0vqzVhG1U8N5QEOvUDL_kM1tdY-B4oTeUMUJk9bp_aUq1t407HctiUyKcpMOuhxJJcu9j-sFO1rDOgw3Ts73e8m-CiwhsK9C9-xMAS0iDUgpnTPFewCZ6D1H0a-IVUfa',
    date: {
      EN: 'Saturday, Sept 12, 2026',
      FR: 'Samedi 12 sept. 2026',
      ES: 'Sábado 12 sept. 2026',
    },
    time: '19:00 - 22:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Willibrord Park BBB Rink',
      FR: 'Patinoire BBB du parc Willibrord',
      ES: 'Pista BBB del parque Willibrord',
    },
    endLocation: undefined,
    category: {
      EN: 'Roller Dance',
      FR: 'Roller Dance',
      ES: 'Roller Dance',
    },
    type: 'social',
    day: 2,
    iconName: 'music',
  },

  // Day 3 - Sunday, Sept 13
  {
    id: 'time-d3-1',
    title: {
      EN: 'Lachine Canal 50K Marathon',
      FR: 'Marathon 50K du Canal de Lachine',
      ES: 'Maratón 50K del Canal de Lachine',
    },
    description: {
      EN: 'The supreme endurance challenge. Draft lines, pace groups, and sprint checkpoints across 50 kilometers.',
      FR: 'Le défi d\'endurance ultime. Lignes de drafting, groupes d\'allure et points de passage sur 50 km.',
      ES: 'El reto supremo de resistencia. Grupos de ritmo, relevos y control de velocidad a lo largo de 50 km.',
    },
    longDescription: {
      EN: 'A test of stamina and technique. This 50km circuit runs along Montreal’s scenic Lachine Canal paths and outer port areas. Designed for endurance skaters who love drafting and continuous pace.',
      FR: 'Un test d\'endurance et de technique le long du canal de Lachine. Conçu pour les patineurs appréciant la vitesse de croisière et le travail en peloton.',
      ES: 'Prueba de resistencia y velocidad por las orillas del Canal de Lachine. Ideal para patinadores que disfrutan del ritmo constante y el trabajo en pelotón.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBtwBSh3I9965A5VA97GMNT6WPcpuu5lY8I0IjGiK64Fk0WHYIT5lLoUPqdrAuZgT135nCSSYXNEfdmjHaaTmCSimZFNPGifGOgEHqV9Ce7EiT2ka47xYp-GUeXAz7mZOk50o73irbImltxqiiVP2kW6I3JS43Y4XX4P68mZoG07MBWF4_BVlxnFnuICCFniVFHWu74Nsja97XezTH6yQTaucqy6wP_2Gzi8Ppx8r-LeFXGjoDfCTB8',
    date: {
      EN: 'Sunday, Sept 13, 2026',
      FR: 'Dimanche 13 sept. 2026',
      ES: 'Domingo 13 sept. 2026',
    },
    time: '09:00 - 12:30',
    level: 'advanced',
    startLocation: {
      EN: 'Lachine Canal Lock 1 (Old Port)',
      FR: 'Écluse no 1 du Canal de Lachine (Vieux-Port)',
      ES: 'Esclusa 1 del Canal de Lachine (Puerto Viejo)',
    },
    endLocation: {
      EN: 'Lachine Lighthouse Park',
      FR: 'Parc du Phare de Lachine',
      ES: 'Parque del Faro de Lachine',
    },
    category: {
      EN: 'Rides',
      FR: 'Randonnées',
      ES: 'Rutas',
    },
    type: 'ride',
    day: 3,
    iconName: 'route',
  },
  {
    id: 'time-d3-2',
    title: {
      EN: 'Braking & Downhill Mastery Workshop',
      FR: 'Atelier Freinage & Maîtrise des Descentes',
      ES: 'Taller de Frenado y Control en Pendientes',
    },
    description: {
      EN: 'Advanced stopping methods (Magic Slide, Soul Slide, Powerslide) and downhill speed control techniques.',
      FR: 'Techniques d\'arrêt avancées (Magic Slide, Soul Slide, Powerslide) et contrôle de vitesse en pente.',
      ES: 'Técnicas avanzadas de frenado (Magic Slide, Soul Slide, Powerslide) y control en descensos.',
    },
    longDescription: {
      EN: 'Learn advanced stopping and downhill control techniques from expert instructors: Magic Slide, Soul Slide, Powerslide variations, carving turns, and safe speed reduction on inclines.',
      FR: 'Apprenez les techniques de freinage et de contrôle en pente avec des entraîneurs d\'expérience : Magic Slide, Soul Slide, Powerslide et virages pour ralentir en toute confiance.',
      ES: 'Aprende métodos de frenado seguro y control de descensos con instructores certificados: Magic Slide, Soul Slide, Powerslide y virajes progresivos.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDGtm6jK2gS9pavNm6jz5SH78XNkpBRlByAo36kawzTStCMCJWYmZDHSmFxJA65lvTw8t7zt04GLIQyw1RzK2wuO05f9ZUaAlWtvbO0aBn3eJYWya9H6nsp3DxS7hNByQEjXU3KTQwIMIXkc0poEBPheC_ZLEE9T_YNzd8qje1-WGGFqKJmuIpyaCUb_hfOnjQh6gB6tvT__tk1NoJ2zBkZsKku1Z9MZ1hdAsg0SCfd8F8nraYwsNCR',
    date: {
      EN: 'Sunday, Sept 13, 2026',
      FR: 'Dimanche 13 sept. 2026',
      ES: 'Domingo 13 sept. 2026',
    },
    time: '13:00 - 14:30',
    level: 'intermediate',
    startLocation: {
      EN: 'Verdun Riverside Slope Area',
      FR: 'Zone en pente des Berges de Verdun',
      ES: 'Área inclinada de la Ribera de Verdun',
    },
    endLocation: undefined,
    category: {
      EN: 'Workshop',
      FR: 'Atelier',
      ES: 'Taller',
    },
    type: 'workshop',
    day: 3,
    iconName: 'school',
  },
  {
    id: 'time-d3-3',
    title: {
      EN: 'High-Jump & Ramp Battle',
      FR: 'Compétition Saut en Hauteur & Modules',
      ES: 'Competencia de Salto de Altura y Rampa',
    },
    description: {
      EN: 'Clear the bar. Spectacular ramp launches, free jump height battles, and style tricks judged by guest pros.',
      FR: 'Passez la barre. Sauts spectaculaires avec tremplin, saut libre en hauteur et figures de style.',
      ES: 'Supera el listón. Impresionantes saltos de rampa, salto libre de altura y trucos evaluados por jueces invitados.',
    },
    longDescription: {
      EN: 'Gravity-defying action on the waterfront. Using certified launch ramps and adjustable high bars, competitors battle for maximum height (Free Jump) and trick style over obstacles.',
      FR: 'Action aérienne sur les berges. Avec tremplins homologués et barres ajustables, les patineurs s\'affrontent en saut libre de hauteur et démonstration de style.',
      ES: 'Acción acrobática junto al río. Con rampas diseñadas y barras regulables, los participantes compiten por la mayor altura (Free Jump) y trucos con estilo.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAcz5koXIDour-9seud2hMpfMyL-_igvkj8j03j20Zl82np7JbR2LTnhd6xlbVKwvbU9LsACykPpKen2VtNbc5FFrl72JyV5zULmrPzmprHSN6Xz5ZsIqK2Ru3HsHTdGaxGLUb8tsP56qQHAuvq9_jEyWiVxo4BIY6rwuwUL2WbKOn3x-9b94cTQj63E3Al0yVXhOMHS3d0ujSQfuGQf_FhLbd1NYV5vjJMu7TSfeZwWXMuIYwWhj8T',
    date: {
      EN: 'Sunday, Sept 13, 2026',
      FR: 'Dimanche 13 sept. 2026',
      ES: 'Domingo 13 sept. 2026',
    },
    time: '15:00 - 18:00',
    level: 'advanced',
    startLocation: {
      EN: 'Verdun Pump Track & Jump Hub',
      FR: 'Pumptrack et Module Saut de Verdun',
      ES: 'Pumptrack y Módulo de Salto de Verdun',
    },
    endLocation: undefined,
    category: {
      EN: 'Competition',
      FR: 'Compétition',
      ES: 'Competición',
    },
    type: 'competition',
    day: 3,
    iconName: 'flight_takeoff',
  },
  {
    id: 'time-d3-4',
    title: {
      EN: 'Grid Closing Awards & Social',
      FR: 'Remise des Prix & Cérémonie de Clôture',
      ES: 'Premiación y Ceremonia de Clausura',
    },
    description: {
      EN: 'Podium awards for Slalom, Marathon, and Jump. Crowning of MTL ROLL 2026 champions. Final celebration.',
      FR: 'Podiums et récompenses pour le Slalom, le Marathon et le Saut. Célébration de clôture MTL ROLL 2026.',
      ES: 'Podio y entrega de premios para Slalom, Maratón y Salto. Celebración final de MTL ROLL 2026.',
    },
    longDescription: {
      EN: 'Official closing ceremony and podium awards for Slalom, Marathon, and Jump competitions. Crowning of MTL ROLL 2026 champions followed by a waterfront celebration.',
      FR: 'Cérémonie officielle de clôture et remise des médailles pour les compétitions. Célébration conviviale au bord de l\'eau pour terminer la fin de semaine en beauté.',
      ES: 'Ceremonia oficial de clausura y entrega de premios de las competencias de Slalom, Maratón y Salto, con fiesta final frente al río.',
    },
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBk23iiPsQondimS8L4yxRofJ4bhsP047QTlBPD9Q2yAq81d3NVWmJPkMoTr-538WC-BYjgSUwL2KujXsd86RSSIWoIUPFWDCjC5znhkqE4sNF6ERE4RBrz1NAHjpvdYcCzVPhl3-Zxr86kRXEL4pew3b0hF0wcEmcXlS-W5jMlp00OGwHKc4tUvXNDcF2u6iZERWETMLoSwYmpfSpLYCqlrL4J03o2ZyXAxyJT3Z-l3270gFsqfT5g',
    date: {
      EN: 'Sunday, Sept 13, 2026',
      FR: 'Dimanche 13 sept. 2026',
      ES: 'Domingo 13 sept. 2026',
    },
    time: '18:30 - 20:00',
    level: 'first_timer',
    startLocation: {
      EN: 'Verdun Waterfront Plaza',
      FR: 'Plaza des Berges de Verdun',
      ES: 'Plaza Costera de Verdun',
    },
    endLocation: undefined,
    category: {
      EN: 'Social',
      FR: 'Rassemblement',
      ES: 'Social',
    },
    type: 'social',
    day: 3,
    iconName: 'trophy',
  },
];
